### ISSUE TITLE
Warning issue around MvxAdapter code

### ISSUE THREAD

**Issue by monesprit54** [MvvmCross/MvvmCross#1004]
In MvxAdapter, MvvmCross checks whether an ItemSource is IList or not, and says
"Binding to IEnumerable rather than IList - this can be inefficient, especially for large lists"

But I think that it should be vice versa like..
"Binding to IList rather than IEnumerable - this can be inefficient, especially for large lists"
since IList is preferred to IEnumerable as I understand? 

https://github.com/MvvmCross/MvvmCross/blob/3.2/Cirrious/Cirrious.MvvmCross.Binding.Droid/Views/MvxAdapter.cs#L140

Please check this.

**Comment by Cheesebaron** [comment]
The wording is correct. Lets decompose it:

- Binding to IEnumerable <-- that is what you are doing right now
- rather than IList <-- what you should be doing
- this can be inefficient, especially for large lists <-- why binding to IEnumerable is bad

**Comment by monesprit54** [comment]
Knew the idea that IList is better than IEnumerable since if you use a class implementing IEnumerable you gotta call "MoveNext()" so many times (n times from the head) if you wanna see n-th item. Instead, when you use a descendant of IList as an ItemSource you can just read the value since IList let you access the item randomly.

The wording "Binding to IEnumerable rather than IList" means you should bind to "descendants of IEnumerable" which is the exact opposite of the wording it intended to be, I guess.

Checks the following link
http://en.wiktionary.org/wiki/rather_than

**Comment by slodge** [comment]
Thanks

As an English Englishman.... let's cut this short....

`Binding to IEnumerable rather than IList - this can be inefficient, especially for large lists` is **not** ambiguous to me....

However, I can see how it might be ambiguous globally...

If anyone wants to send a pull to something like `You are currently binding to IEnumerable - this can be inefficient, especially for large collections. Binding to IList is more efficient.` then we'd happily accept it.

People are different - and language structures are different... which is the way we love it :)

![Confusing](http://upboat.me/ay/Words/confusing-they-are.jpg)

**Comment by Cheesebaron** [comment]
[**@monesprit54**](https://github.com/monesprit54) commented on [May 12, 2015, 6:51 PM GMT+2](https://github.com/MvvmCross/MvvmCross/issues/1004#issuecomment-101346085 "2015-05-12T16:51:29Z"):
> Checks the following link
> http://en.wiktionary.org/wiki/rather_than

That wiktionary is really a bad example. You can't really always say that the statement following "rather than" is always less preferred.

**Comment by monesprit54** [comment]
Hey Tomasz,

Haha

After having a nice sleep, now I see the point what I thought wrong.

I somehow understood the wording as "Bind to IEnumerable rather than
IList!! The thing you are doing is inefficient"



2015년 5월 13일 수요일, Tomasz Cielecki<notifications@github.com>님이 작성한 메시지:
