### ISSUE TITLE
App crash on orientation change. 

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#1081]
I ran into a crash in my app and I think it has to do with fragments with this view pager adapter.  My portrait only fragment launches a Camera intent to take a picture.  The camera intent launches landscape by default.  I take the picture and control returns back to my app, but I think an orientation change has happened and my app crashes.  After some debugging, I detect that the parent Activity has a valid ViewModel but my fragment has a null ViewModel.  I was reading some SO posts and I think I have to do something to manually reattach the ViewModel to the fragments.  Do you have any examples or suggestions on doing this?

by the way, I don’t have to recreate the fragment ViewModels as they are still present inside the parent Activity’s ViewModel.  I just have to reattach them to the fragments.

**Comment by martijn00** [comment]
There is an example of using viewpager with mvvmcross available here: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Droid/Fragments/ExamplesFragment.cs

The thing you might want to look at is https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.V4/MvxFragmentStatePagerAdapter.cs#L63

We block restoring of the viewpager there because it makes the app crash on rotation.
