### ISSUE TITLE
onTrimMemory is used only for API level 14 , I need to detect when app is backgrounded for api level <14 

### ISSUE THREAD

**Issue by sabrinemoumni** [MvvmCross/MvvmCross#1105]
What can I do to detect when app is backgrounded like new relic 
I should'nt use the life cycle of activity

**Comment by Cheesebaron** [comment]
Why do you use `OnTrimMemory` to detect whether an app is in the background? That is not pretty at all. You could have a service which detects if the app is in the background like in this kiosk mode sample: https://github.com/Cheesebaron/KioskModeSample/blob/master/KioskMode/KioskService.cs#L59

Otherwise use `OnStop` and `OnStart` on your `Activity` to track whether it is in the background or not.

**Comment by sabrinemoumni** [comment]
ok I test this method but I have a  fear , I wonder if it needs more resources of cpu and memory cause I will get all running task every second for exemple ?
concerning the life cyle, I can't intercept these methods
