### ISSUE TITLE
Make MvxOwnedViewModelFragment Opt-out instead of in

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1138]
This was changed in https://github.com/MvvmCross/MvvmCross/pull/915

Since we can break things in 4.0 i would suggest making this Opt out by renaming `MvxOwnedViewModelFragment` to `MvxNotOwnedViewModelFragment` or something.

**Comment by kjeremy** [comment]
I think it makes more sense to opt in to a feature than to opt out especially where fragments are concerned (they aren't just for UI purposes).

**Comment by vvolkgang** [comment]
I still don't understand the impact of having / not having this, that being set, if The Right Way™ indicates that this should be always used, I vote for this to be made by default. 

"Less code, less bugs."
- Someone really wise

**Comment by vvolkgang** [comment]
@kjeremy whats the expected behaviour / usecases of having that set vs not having? All the issues only refer it as "pre-3.0 behaviour", didn't found anything stating what it is exactly.

**Comment by kjeremy** [comment]
There are a lot of times where you don't want your fragments managed by MvvmCross's fragment tracking stuff (some viewpager user, slide in ui elements, retained instance fragments).  Plus Activities already require an `ActivityAttribute` whereas normal Fragment's do not so by making this opt-in behavior we can also keep them stylistically similar.

**Comment by vvolkgang** [comment]
@kjeremy but what does "being managed by mvx fragment tracking" implies then? Using `MvxCachingFragmentActivity.RegisterFragment(...)` is supposed to do the same?

**Comment by davidschwegler** [comment]
As the author of #915 and #908 I'll just echo what kjeremy's saying -- MvvmCross's automatic management handles specific scenarios of how fragments are used in an "ideal" sense. That is not the case as/more often than it is -- probably 75% of our fragments don't support that automatic scenario, while most still support having a ViewModel directly set on them. An opt-out should really only be a thing if it was really, really rare that you'd want to opt-out. 

This is just a bonus MvvmCross can provide if you know your scenario supports it. From my experience, most new devs assume defaults work, which lets crashes sneak in because they don't really understand the impact this behavior has in the edge cases.

**Comment by martijn00** [comment]
Thanks everyone for explaining your concerns! This will not be changed for now. There is a PR of @thefex which will make this more easy to handle with opt-in. That will be the current solution for this issue.

**Comment by kjeremy** [comment]
Thanks for explaining this **way** better than I could @davidschwegler.
