### ISSUE TITLE
Enable ShowViewModel to take a view model instance

### ISSUE THREAD

**Issue by SamirHafez** [MvvmCross/MvvmCross#1141]
I'm thinking of the following situation: 

A view model that holds a collection of other view models (as opposed to simple POCOs). This happens because I intend to show the (varying) number of likes a photo has when displaying it as a list item. When I select one, I would like to take advantaged of the already created view model and just show it in a different activity/fragment/whatever...

```
public class AlbumViewModel : MvxViewModel
{
    ObservableCollection<PhotoViewModel> photos;
    public ObservableCollection<PhotoViewModel> Photos
    {
        get { return photos; }
        set { SetProperty(ref photos, value); }
    }

    MvxCommand<PhotoViewModel> photoSelectedCommand;
    public MvxCommand<PhotoViewModel> PhotoSelectedCommand =>
        photoSelectedCommand ?? (photoSelectedCommand = 
            new MvxCommand<PhotoViewModel>(NavigateToPhoto));

    void NavigateToPhoto(PhotoViewModel photo)
    {
        ShowViewModel(photo);
    }
}

public class PhotoViewModel : MvxViewModel
{
  string url;
  public string Url
  {
    get { return url; }
    set { SetProperty(ref url, value); }
  }

  int liked;
  public int Liked
  {
    get { return liked; }
    set { SetProperty(ref liked, value); }
  }

  //POOLING SERVICE THAT REFRESHES LIKES
  //...
}

```

A scenario like this is not easy to achieve without the ability to navigate to a previously instantiated view model.

What do you guys think?

**Comment by Cheesebaron** [comment]
The problem is the way you communicate between Activities, you can't just pass on an object in an Android `Bundle`. They either need to be a `Parcelable`, which means they will get serialized and deserialized anyways, or they need to be a simple type such as a string, int, bool etc.

On previous Windows Phone platforms this was also the case. Although we were limited to the size of the URL passed around to navigate between Pages.

So what do you suggest here?

**Comment by SamirHafez** [comment]
Sorry for the delay...

Okay, so get this:
I was thinking the ShowViewModel method could add the view model to a hash table and pass the hash in the bundle.
Then, we override MvxDefaultViewModelLocator to (if the bundle has a hash) retrieve it instead of creating a new one.

**Comment by Cheesebaron** [comment]
It would still be a copy of the ViewModel and not the actual instance.

**Comment by SamirHafez** [comment]
How come?
The instance that goes in the hash table is same retrieved by the ViewModelLocator

**Comment by slodge** [comment]
It can be done.... and it has been done in the past for, for example, tabs in iOS UI

However, there are some things to consider:
1. How will this design cope with app tombstoning and rehydration?
2. How will this design cope with the back button
3. How will this design know when to remove the reference to the ViewModel to avoid the singleton hash table holding on to it "forever"
4. How do you help users to understand the limitations of this method (especially understanding tombstoning...)
5. How does this tie in to the lifecycle Mvx users expect in a viewmodel (e.g. Init, Start)
6. etc (there's always more to think about ;))

Those need working through...

----

Also note that in your original Album and Photo design, you could manage this all in the Viewmodel and Service layers - you could manage your own `cache` of `Photo` model objects (implementing INPC) and you could have a very thin `PhotoViewModel` implementation which maps through to `Photo`... It's not that unusual for model objects to implement INPC (rather than being POCOs) - e.g. I have fond memories of writing an app that used Stacky POCO objects like - http://stacky.codeplex.com/SourceControl/latest#trunk/source/Stacky/Entities/Answer.cs

**Comment by martijn00** [comment]
Implemented in https://github.com/MvvmCross/MvvmCross/pull/1840
