### ISSUE TITLE
Win10 Uap + MvxSuspensionManager + .Net Native 

### ISSUE THREAD

**Issue by Gert-Cominotto** [MvvmCross/MvvmCross#1148]
Hello,

Yesterday I found a bug in the MvxSuspensionManager when building the solution with .Net Native. 
It all works well when building in Debug, but when I switch to Release (which gets build with the .Net Native toolchain), I get an error on the 3rd line:

``` csharp
var sessionData = new MemoryStream();
var serializer = new DataContractSerializer(typeof(Dictionary<string, object>), _knownTypes);
serializer.WriteObject(sessionData, _sessionState);
```

the error itself:
Exception: SerializationCodeIsMissingForType. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485, Stack:    at [MyNameSpace]!<BaseAddress>+0xa3ba13

I created a basic test application which you can find here:
http://1drv.ms/1KR6W7n

I'm trying to fix this myself, but without any success, if I get something that works, I'll share it of course!

Kind regards,
Gert

**Comment by SGuyGe** [comment]
I took a look at the basic test application. The reason for the failure is because serialization code for Dictionary<string, string> was missing. To solve the problem, you'll need to provide hint to .NET Native compiler with either of the following approaches:

1. Change the code in debugsuspensionmanager.cs, line 34:
        private readonly List<Type> _knownTypes = new List<Type>() { typeof(KeyValuePair<string, string>) }; //Bundles are saved as string-string dicts, serializer needs to be warned of this type or will throw.
=>
        private readonly List<Type> _knownTypes = new List<Type>() { typeof(Dictionary<string, string>) }; //Bundles are saved as string-string dicts, serializer needs to be warned of this type or will throw.

2. Add the following into Default.rd.xml:
    <TypeInstantiation Name="System.Collections.Generic.Dictionary" Arguments="System.String, System.String" Dynamic="Required All" DataContractSerializer="Required All" />

Please give it a try.

**Comment by Gert-Cominotto** [comment]
Thanks @SGuyGe for taking a look, but these 2 approaches didn't fix it for me.
Did you get this working yourself?

Kind regards,
Gert

**Comment by SGuyGe** [comment]
Where did you try these 2 approaches? Have you tried them on the basic test application you shared out? If you can share the repro app I can take another look.

**Comment by Gert-Cominotto** [comment]
I tested this yesterday with the  basic test app I provided above. 
The only extra change I did was update the mvvmcross packages to the latest beta.

**Comment by SGuyGe** [comment]
Yes, I got it working myself. I just tried it again, but this time only #2 works while #1 doesn't. Since #1 isn't guaranteed to always work, I've removed it in above comment.

Here're the steps I performed:
1. Unzip your repro, open with VS and update NuGet package to use the latest MvvmCross.
2. Build release configuration and F5. Click Navigate button, the form turns red, close the form, it crashes.
3. Modify default.rd.xml as mentioned in my previous comment.
4. Build and F5. Click Navigate button, the form turns red, close the form, it exits without problem.

Please try it again. If it still doesn't work, please write down your steps so that I can try.

**Comment by Gert-Cominotto** [comment]
Hey @SGuyGe,

This does work!
Not sure what I did different last time, but I've got it working.

Here's the working repo if needed:
http://1drv.ms/1VdxDcu

Thanks for the help!

**Comment by Gert-Cominotto** [comment]
Damn, maybe shouldn't have closed this?
Would be nice if this could be fixed in v4

**Comment by SGuyGe** [comment]
My pleasure. Good to here that it's working for you now!
