### ISSUE TITLE
Add support for the new Xamarin.tvOS target platform

### ISSUE THREAD

**Issue by Stephanvs** [MvvmCross/MvvmCross#1153]
Well, since there is now a preview release for the new Apple TV, we could consider adding support for it in MvvmCross as well.

I'm not really sure what needs to happen to onboard a new platform. I do know that most API's will be similar to the Xamarin.iOS ones, just that we're probably going to need different project types, because there'll be a new project type for tvOS projects.

**Comment by martijn00** [comment]
In https://github.com/MvvmCross/MvvmCross/pull/1101 we added UWP support. About the same should be done for tvOS.

**Comment by Dexyon** [comment]
I am currently working on the set-up. However, in Xamarin Studio we cannot create a TvOS library yet which is required for building new libraries. 

Referencing iOS libraries causes import errors (due to references to Xamarin.iOS instead of Xamarin.TvOS), as expected of course!

Will update this issue when I get some more feedback from Xamarin regarding the library approach!

**Comment by Stephanvs** [comment]
It's correct that the normal alpha channel doesn't have support for tvOS yet, however there's a prerelease version available with support. Check out this forum post: http://forums.xamarin.com/discussion/52476/xamarin-ios-9-3-preview-for-ios-9-1-tvos-9-0-and-watchos-2-0 you should also download the tvOS SDK from the Apple Member Center.

**Comment by Dexyon** [comment]
@Stephanvs I have the preview installed together with the Xcode beta and even the dev-kit. However, in Xamarin Studio we can only create a TvOS app and not a library.

**Comment by webmonger** [comment]
I have a working configuration/frankenstein of MvvmCross and TvOS. It's hardly what I would call an implementation as TvOS projects don't support PCLs so linking to the core project is done by finding the DLL in the bin folder. Also the way I have implemented MvvmCross is by just copying all the files required in to the single TvOS shared library.

Anyway it works, I'm going to try and tidy it up as much as I can. I'm sure as the preview moves towards alpha support for new projects will be added as will PCL support.

If you want to see whats been done so far let me know.

**Comment by Dexyon** [comment]
Do you have examples of the work that you have done?

**Comment by webmonger** [comment]
You mean for TvOS or using MvvmCross?

**Comment by webmonger** [comment]
I just pushed a much tidier version of my previous POC to a fork

@Dexyon @Stephanvs You can download the source at https://github.com/webmonger/MvvmCross

You'll need to build the solution and then pull the dlls in to your TVOS project manually, in a bit I'll upload an example project. I warn you it's VERY basic but it builds and runs with the pre Alpha from the forum ;)

Are there any sample projects you can recommend that I could add a TVOS UI to, it's been a while since I used any samples?

**Comment by webmonger** [comment]
Example project can be found at https://github.com/webmonger/MvvmTVOS

**Comment by martijn00** [comment]
Xamarin has updated their release: https://releases.xamarin.com/preview-watchos-2-0-tvos-second-preview/

**Comment by Dexyon** [comment]
@webmonger I did a quick look at your project, but it still includes most of the phone/ipad checks. Maybe we should take a look at what really should be there instead of making an TvOS copy of the iOS code?

**Comment by webmonger** [comment]
@Dexyon yeah the code is purly a POC for my team to look at.

I wonder whether keeping the codebases together would be a better idea and excluding the files/code in tvOS that is not required. There is very little difference between iOS and tvOS maintanance would be much easier if compile flags were used rather than duplication of all the code.

Unfortunatley because the tools were not really available at the time to create the projects I created them by hand which has it's draw backs ;)

**Comment by Stephanvs** [comment]
I think the best way forward to introduce multiple Apple platform support is the new intersection nugets as announced in preview on the forums yesterday: http://forums.xamarin.com/discussion/55255/sharing-code-across-apple-platforms.

I'm going to take a stab at it.

**Comment by Cheesebaron** [comment]
:hocho: :skull:

**Comment by Dexyon** [comment]
@Stephanvs Wow, missed that announcement! Finally!

**Comment by martijn00** [comment]
Fixed in: https://github.com/MvvmCross/MvvmCross/pull/1448
