### ISSUE TITLE
Data binding without a ViewModel

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#1156]
I am doing something I have never tried before.  I am trying to create dynamic UI and bind it to a dynamic model.  In other words, my web service is going to send back a small metadata description of my UI and the raw data to bind to it.  Therefore, at build time, I don't know what UI I will be constructing and I don't know what my model will be.  Binding them together seems VERY difficult if not impossible.

Mvx allows me to bind UI directly to a model WITHOUT it being an MvxViewModel.  However, if I bind directly to the Model returned by the web service, I lose the ability to RaisePropertyChanged() since that only comes from MvxViewModel.

Normally, I would write a ViewModel that wraps the Model and have all the wrapped setters call RaisePropertyChanged().  However, in this case, my model is dynamic so I can't wrap it with a ViewModel at compile time since I don't know what it is until runtime.

Is there some cool trick I can use to construct a ViewModel that can wrap any C# model class and send out property changed events without knowing what properties the model class has until runtime?

**Comment by Cheesebaron** [comment]
This probably belongs on StackOverflow rather than here.

**Comment by scastria** [comment]
Yes, but am I the only one that feels posting anything to SO will get lost in the thousands of other posts?  I would love it if GitHub added forums for each project.  Therefore, I know that I can go to one place to see everything related to MvvmCross.  I don't have to worry that my SO tags aren't set correctly for someone to see my post.

Just like with Xamarin, I can go to their forums and post there and feel confident that someone will see it and perhaps respond.  I have no confidence that will happen with SO.

That is why I posted here.

However, since there is only 1 SO tag called MvvmCross, I guess it is pretty clear where to go for MvvmCross stuff.  I will close this.

**Comment by Cheesebaron** [comment]
Well this question isn't even directly related to MvvmCross, but rather about "misusing" the MVVM design pattern. So I am inclined to say that you should not even use the MvvmCross tag on SO for this question in particular, but rather the general MVVM tag.

Anyways, why I ask you to post on SO instead of here, is that as you can see, we currently have approximately 130 issues open in the main repo. If everyone were asking questions here, these issues were going to drown in all people's questions, making them harder to find.
Don't get me wrong, we do appreciate you asking questions, and yours is quite interesting. However, we want to keep GitHub strictly to issues.
