### ISSUE TITLE
UWP TipCalc tutorial

### ISSUE THREAD

**Issue by rubenvb** [MvvmCross/MvvmCross#1161]
I tried to stitch together the various tutorials to come up with a functional Windows 10 UWP TipCalc app, but I failed. Currently I can't find a way to resolve this error:

     ...\TipCalc\TipCalc.UI.Windows\Views\TipView.xaml.cs(26,31,26,38): error CS0509: 'TipView': cannot derive from sealed type 'TipView'

The source for this project is available in my github repo:
https://github.com/rubenvb/App-Playground/tree/master/TipCalc

Any help, or a full-blown Windows 10 UWP tutorial would be great! It seems some magic is still required to get this to work, hence this issue report.

**Comment by EMarshal** [comment]
I don't think you were far off:

* I think you're missing some files from your project, in particular TipView.xaml.cs isn't present.
* The common files (NavigationHelper, ObservableDictionary, RelayCommand, SuspensionManager) are missing - steps for these are in the current UWP TipCalc tutorial, you may have skipped the dialog to add these.
* TipCalc.UI.Windows was causing some havoc with namespace collision with Windows - TipCalc.UI.WindowsCommon works. (Or WindowsUWP would be more consistent with MvvmCross nomenclature.)
* You want the TipView.xaml page to be have a root node of views:MvxWindowsPage, since the tutorial was written the namespace for this has switched from Cirrious.MvvmCross.WindowsCommon.Views to Cirrious.MvvmCross.WindowsUWP.Views.

I don't think the (current tutorial)[https://github.com/MvvmCross/MvvmCross/wiki/Tip-Calc-A-Universal-Windows-App-UI-Project] is bad, other than outdated namespaces.

**Comment by rubenvb** [comment]
I must have found an old version somehow. It seems it's been updated quite a while ago. And all this time I thought it wouldn't work. Stupid me. Thanks for the professional help!
