### ISSUE TITLE
Android use Custom ViewFactory 

### ISSUE THREAD

**Issue by smstuebe** [MvvmCross/MvvmCross#1271]
Today, I tried to add a custom view factory for Android. In my case it should set a custom font and some other properties. I have committed an example to https://github.com/smstuebe/mvx-custom-view-factory In the example, the factory simply sets the background color. The problem is, that bindings are no longer working. I had a intense look at `MvxLayoutInflater` but I can't find a way to inject my custom factory :( How can I do this?

    [Activity(Label = "View for FirstViewModel")]
    public class FirstView : MvxActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            LayoutInflater.Factory = MyViewFactory.Instance;
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.FirstView);
        }
    }

### Steps to reproduce

1. checkout the linked repository
2. start the app -> no binding works
3. remove `LayoutInflater.Factory = MyViewFactory.Instance;` and start again -> bindings are working

### Expected behavior
Binding works with custom View Factory.

### Actual behavior
Binding and custom View Factory are not working in combination.

### Configuration

**Version:** 4.1.0

**Platform:** Android

**Comment by kjeremy** [comment]
You're doing it wrong :)

`LayoutInflater`s are a little weird.  You can't just attach your factory to the existing layout inflater.

Instead you need to get the right `LayoutInflater` (which is usually an instance of `MvxLayoutInflater` in MvvmCross but you don't need to know that)  then attach your custom factory to it.

ex:
```csharp
var newInflater = LayoutInflater.From(context)
newInflater.Factory = myCustomFactory;
```

You MAY need to `CloneInContext` the result of `LayoutInflater.From` but I don't think so.

**Comment by kjeremy** [comment]
Yeah if that doesn't work try:

```csharp
var originalInflater = LayoutInflater.From(context);
var newInflater = originalInflater.CloneInContext(originalInflater.Context);
newInflater.Factory = myCustomFactory;

// use your new inflater here...
```

**Comment by smstuebe** [comment]
No. As I understand the code, the `MvxLayutInflator` should handle setting the factory properly. That's why I set it via `LayoutInflater.Factory = MyViewFactory.Instance;`

    var li = LayoutInflater as MvxLayoutInflater;
    li.setFactory(MyViewFactory.Instance); 

Is working. I assume, that the `Export` attribute on `setFactory` is not doing, what is asserted here: https://bugzilla.xamarin.com/show_bug.cgi?id=30764 or something else is wrong with the `Factory` property.

**Comment by kjeremy** [comment]
I wrote that bug which is why I had to mess with `setFactory` :(

`MvxLayoutInflater` is essentially an implementation of the visitor pattern.  It has to visit every `View` created including those that are returned from custom factories.  In order to do that we have to wrap every attached 'IFactory' and 'IFactory2' in some code that is responsible for binding the views.  We also have to get at the views returned by the base implementation which means some terrible hacks to reimplement how the Android framework instantiates views.  If the Android team had supplied a callback this would have been so much easier...

Anyway if that bug still exists then it would explain why you are losing your binding.  You are replacing our factory with your own.  Regardless I would avoid calling `setFactory` directly as there are some nasty platform bugs (See https://github.com/MvvmCross/MvvmCross/blob/db518ac46945b00b0bb5e0c68a116aa5c313b658/MvvmCross/Binding/Droid/Binders/MvxLayoutInflaterCompat.cs#L57).  This is why they introduced the support library's `LayoutInflaterCompat`.  Instead I would just do the following in your activity:

```
LayoutInflaterCompat.SetFactory(LayoutInflater, new MyViewFactory(context));
```

That should correctly merge the factories.

**Comment by smstuebe** [comment]
Yes. the `LayoutInflatorCompat` is working, too.

**Comment by kjeremy** [comment]
@martijn00 I can't close this issue.  Please close.

**Comment by HEBOS** [comment]
Guys, I think it is better to register custom MvxAndroidViewFactory and register it as singleton in your setup.cs

public class RobotoTextFactory : MvxAndroidViewFactory
{
public override View CreateView(View parent, string name, Context context, IAttributeSet attrs)
        {
            var view = base.CreateView(parent, name, context, attrs);

            var attributeValue = attrs.GetAttributeIntValue("http://schemas.android.com/apk/res-auto", "typeface", -1);

            if (attributeValue >= 0)
            {
                try
                {
                    var textView = view as TextView;

                    if (textView == null)
                        return view;

                    var font = ObtainTypeface(context, attributeValue);

                    textView.SetTypeface(font, _mStyle);
                    return view;
                }
                catch (Exception)
                {
                }
            }

            return view;
        }
}

Register it in your setup.cs
SimpleLocator.Current.RegisterSingleton<IMvxAndroidViewFactory>(() => new RobotoTextFactory());
