### ISSUE TITLE
4.5MB of MvxFragmentAttribute generated when starting up https://github.com/Noires/MvxRecyclerViewLeakTest

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1368]
Open your xamarin profiler and check out how many `MvxFragmentAttribute` are created at startup.

**Comment by Noires** [comment]
@kjeremy Does this still need to be checked? Finally got the profiling working without xs or vs.

**Comment by kjeremy** [comment]
@Noires yes.  You can see my work on [optimize-mvxfragment](/kjeremy/MvvmCross/tree/optimize-mvxfragment) however I'm not sure it helped much.

**Comment by martijn00** [comment]
@kjeremy I guess we can pull this in and wait for feedback, at least at first glance it looks good!

**Comment by kjeremy** [comment]
I haven't submitted it as a PR yet.

**Comment by Noires** [comment]
Well without the changes i get 4.5MB of `MvxFragmentAttribute ` aswell. Though iam not able to get the application running with the changes, prolly cus i just included the changes in the current Droid.Shared and Droid.Support.V4 instead of FullFragging?

Basically just getting a `MvvmCross.Platform.Exceptions.MvxException: ToFragment called on an IMvxFragmentView which is not an Android Fragment: OverViewFragment{1c0d65df #0 id=0x7f06006c MvxRecyclerViewLeakTest.ViewModels.OverViewViewModel}` followed by a SIGSEV.

**Comment by nmilcoff** [comment]
As `MvxFragmentAttribute` doesn't exist anymore and a lot of code about fragments has changed when the new AndroidViewPresenter was introduced, I'm closing this issue. If this happens with the new presentation attributes, it would be better to have a new issue opened.
