### ISSUE TITLE
Switch to ViewHolder pattern instead of wrapping in FrameLayout for MvxListView items

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1465]
Currently we have a dummy `MvxListItemView` which itself is a `FrameLayout`, meaning we wrap every item in the list in an additional `FrameLayout` adding another layer to the onion.
This exact wrapping also breaks adjusting `RadioButton`s inside of a `RadioGroup`, since the View hierarchy is looking like:

```
RadioGroup (LinearLayout)
    FrameLayout
        RadioButton
    FrameLayout
        RadioButton
```

Instead of

```
RadioGroup (LinearLayout)
    RadioButton
    RadioButton
```

This means any layout attribute set on a `RadioButton` is not actually used within the `RadioGroup`.

Using `MvxListItemView` is kind of using the `ViewHolder` pattern. However, I think it should be possible to remove the view nesting, just like we do in MvxRecyclerView in the Support library.

**Comment by orzech85** [comment]
I am working currently on this issue. My idea is to remove inheritance from FrameLayout and pass parent from adapter instead. The problem is that MvxListItemView has also responsibility for caching data context dependent on own lifecycle (OnAttachedToWindow() and OnDetachedFromWindow()) and implement ICheckable. I am going to move first responsibility to first child, but currently I have no idea what to do with ICheckable... I will think tomorrow about it, but maybe someone has some ideas about that.

**Comment by Cheesebaron** [comment]
@orzech85 try look at the implementation of ViewHolder in MvxRecyclerView.

**Comment by orzech85** [comment]
I have tried, but ViewHolder pattern is build-in in RecyclerView.Adapter in contrast to Adapter for ListView. eg. callback method OnViewAttachedToWindow exists in RecyclerView.Adapter itself.

**Comment by Cheesebaron** [comment]
But does the "ViewHolder" for a `BaseAdapter` need to be a view. Can't it just contain a inflated view, which you subscribe to that views lifecycle events? 
Haven't looked into this much further, but wrapping all rows in an additional view is what is breaking the layout of rows for all `AdapterViews` that use `MvxAdapter`.

**Comment by orzech85** [comment]
Yes, sure. I will try hack on this today.
