### ISSUE TITLE
Create new event hooks for lifecycle events

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1531]
There is a great discussion on the Xamarin Forums: https://forums.xamarin.com/discussion/84510/proposal-improved-life-cycle-support discussing where to hook into lifecycle events that are similar on all platforms.

It would be great to expose these in the ViewModels, but also make sure we are loading stuff the correct places.

This is part of #1415

**Comment by Strifex** [comment]
So I took a brief look at this from the Android side and there's quite a few challenges involved, so I thought I'd share my findings.  

- If we were to use OnAttachedToWindow and OnDetachedFromWindow per the suggestions in the xamarin discussion thread, only Activity Classes and some of the custom views in the android support library have those available to them, the MvxFragment class does not.

- Given the complexity of the fragment life-cycle, finding an event to hook into to simulate "Appearing" and "Disappearing" may not be possible and they'll have to be emulated.

- Not only will we have to account for Acitivity/Fragment classes but we should also override custom android views such as MvxRecyclerView/MvxListView/etc. in case consumers are data-binding collections of viewmodels to those "controls".

So given those complications, I think it would be wise to create an agreed-upon "spec" before anyone starts on implementing this.  If we're not careful the events we setup could cause some wonky behavior in certain cases, especially when it comes to 'resuming' fragments and their viewmodels on android.

**Comment by kjeremy** [comment]
MvxFragment supports attach/detach.

On Dec 17, 2016 6:43 PM, "Robert Till" <notifications@github.com> wrote:

So I took a brief look at this from the Android side and there's quite a
few challenges involved, so I thought I'd share my findings.

   -

   If we were to use OnAttachedToWindow and OnDetachedFromWindow per the
   suggestions in the xamarin discussion thread, only Activity Classes and
   some of the custom views in the android support library have those
   available to them, the MvxFragment class does not.
   -

   Given the complexity of the fragment life-cycle, finding an event to
   hook into to simulate "Appearing" and "Disappearing" may not be possible
   and they'll have to be emulated.
   -

   Not only will we have to account for Acitivity/Fragment classes but we
   should also override custom android views such as
   MvxRecyclerView/MvxListView/etc. in case consumers are data-binding
   collections of viewmodels to those "controls".

So given those complications, I think it would be wise to create an
agreed-upon "spec" before anyone starts on implementing this. If we're not
careful the events we setup could cause some wonky behavior in certain
cases, especially when it comes to 'resuming' fragments and their
viewmodels on android.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MvvmCross/MvvmCross/issues/1531#issuecomment-267794293>,
or mute the thread

**Comment by Strifex** [comment]
If I remember correctly, Attach/Detach isn't the same thing as OnAttachToWindow. I think in the lifecycle it occurs before OnAttachToWindow in the activity, this means a fragment would get its OnAppearing called before its parent activity, no?

**Comment by kjeremy** [comment]
Good point.  You are right in that they are not the same.

**Comment by martijn00** [comment]
I've started on this in the https://github.com/MvvmCross/MvvmCross/tree/eventhooks branch. Feel free to help out where parts are missing.

**Comment by Cheesebaron** [comment]
The branch is deleted, see #1601 instead.
