### ISSUE TITLE
"Partial declarations of 'TestView' must not specify different base classes" error

### ISSUE THREAD

**Issue by syaifulnizamyahya** [MvvmCross/MvvmCross#1547]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Create a project using Ninja Coder MvvmCross template

2. Add new view in .UWP project

3. Replace view inheritance from Page to MvxWindowsPage like below

Original
```
	public sealed partial class TestView : Page
```
Replaced
```
	public sealed partial class TestView : MvxWindowsPage
```

### Expected behavior
No error whatsoever

### Actual behavior
I get this error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0263	Partial declarations of 'TestView' must not specify different base classes	

```

### Configuration

**Version:** 4.x

**Platform:** Windows UWP

**Comment by mvanbeusekom** [comment]
You receive this error because you have a class which is constructed out of two parts (partial classes). Most likely in your case you have a second file called "TestView.designer.cs" which contains the second partial class definition. Make sure this class also derives from the "MvxWindowsPage" class. 

Note, it is possible you don't see the file right away in Visual Studio since it is hidden by default. Make sure you expand the grouping of the "TreeView.cs" file (by clicking on the + icon in front of the file in the Solution Explorer).

**Comment by syaifulnizamyahya** [comment]
Found the solution

I must replace reference to Page class in both .cs and .xaml. My mistake was I only replace Page reference to MvxWindowsPage in .cs only. I forgot to change reference to Page in .xaml

Original(TestView.xaml)
'''
<Page
'''
After fix(TestView.xaml)
'''
<views:MvxWindowsPage
'''
