### ISSUE TITLE
Move APIExampes from MvvmCross-Samples over in main repo

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1576]
There are loads of great examples in the APIExamples project in the samples repo.

I would like to see it moved over here and expand it with isolated samples of features added to MvvmCross, to easily test out when debugging stuff.

**Comment by ghuntley** [comment]
I'm conflicted (personally) on this one. For RxUI I'm considering :burning: all of the playground/samples in the main repository and instead doubling down on a separate repository - https://github.com/reactiveui/samples (currently empty). Then doubling down on CI (as in integration) tests that run the samples against the nuget packages generated to verify that there are no packaging defects and also to run e2e tests on simulator or on Xamarn Test Cloud. Will be interested in seeing how this progresses in Mvx land.

**Comment by Cheesebaron** [comment]
It is just as much easing the job of testing the code while working on MvvmCross, it can be a bit painful to create a new project and add references to relevant parts and set up all the boiler plate.

**Comment by nmilcoff** [comment]
There are currently __a lot__ of TestProjects in the main repo. I think we should gradually move into a single one (or maybe two, if we want to keep a separate one for X.Forms).

I suggest these milestones (not considering Xamarin Forms samples here):
1) Move APIExamples into main repo

2) TestProjects reduction: Keep only APIExamples and Playground (good for testing navigation and presenters). All other projects should be integrated into these two.

3) Unify Playground and APIExamples into a single, big TestProject.

What do you guys think @MvvmCross/core?

**Comment by mvanbeusekom** [comment]
I am in doubt, when I need to learn something or looking for a particular sample I prefer the project to be small and focused on the particular topic (no distractions). The same goes when the projects are only meant as test projects. The bigger they get the harder it becomes to quickly test functionality. Second it might also be difficult to merge all functionality into one project (although this might be a sign the we need to improve certain things). A good example would be combining the Sidebar example with the other iOS navigation structures, this will be difficult in the current implementation since they both require a different presenter. 

Then I also get that the maintenance is hard when having a lot of projects. And as mentioned earlier with a bigger project it is easier to test if different functionalities play nice together. So I am kinda in a limbo ;)

**Comment by nickrandolph** [comment]
@Cheesebaron do we still want to do this? 
Personally I think there are samples that are in the main repo that need to be upgraded and added back to the main solution, but samples that are in the samples repo should probably just stay there and have some tasks raised to get them maintained. Thoughts?
