### ISSUE TITLE
Improve logging and IMvxTrace

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1649]
There is a lot of benefit in using Serilog instead of our current tracing mechanisms. Such as Serilog is easily configurable to log almost anywhere and a lot of plugins have been made to [sink data into a _lot_ of different systems](https://github.com/serilog/serilog/wiki/Provided-Sinks).

I think it would be a great addition to MvvmCross, which would help the developer log errors, enrich log messages with needed information etc.

**Comment by willsb** [comment]
Should Serilog be used as the default implementation of `IMvxTrace` that ships with MvvmCross (meaning MvvmCross would have a dependency on Serilog) or should we create a plugin that wraps Serilog and allows for adding sinks as needed? I prefer the later

**Comment by kjeremy** [comment]
I'm not sure we want a hard dependency on serilog.  I like rxui's implement
ILogger and it just works.

**Comment by Nickolas-** [comment]
I think Plugin will be a good idea for people that not using their own services.

**Comment by willsb** [comment]
I came up with two proposals for this, one more conservative and the other more aggressive. Even if either has flaws, they are still a good starting point for closing this issue.

# Proposal 1 

We create a new plugin that adds this class

```csharp
using System;
using MvvmCross.Platform.Platform;
using Serilog;

namespace MvvmCross.Plugins.Serilog
{
    public class MvxSerilogTrace : IMvxTrace
    {
        private readonly ILogger logger;

        public MvxSerilogTrace(ILogger logger)
        {
            this.logger = logger;
        }

        public void Trace(MvxTraceLevel level, string tag, Func<string> message)
            => Trace(level, tag, message());

        public void Trace(MvxTraceLevel level, string tag, string message)
        {
            switch (level)
            {
                case MvxTraceLevel.Diagnostic:
                    logger.Information(tag + message);
                    break;

                case MvxTraceLevel.Error:
                    logger.Error(tag + message);
                    break;

                case MvxTraceLevel.Warning:
                    logger.Warning(tag + message);
                    break;
            }
        } 

        public void Trace(MvxTraceLevel level, string tag, string message, params object[] args)
        {
            switch (level)
            {
                case MvxTraceLevel.Diagnostic:
                    logger.Information(tag + message, args);
                    break;

                case MvxTraceLevel.Error:
                    logger.Error(tag + message, args);
                    break;

                case MvxTraceLevel.Warning:
                    logger.Warning(tag + message, args);
                    break;
            }        
        }
    }
}
```

One could then simply drop this plugin on their project and replace this:

```csharp
protected override IMvxTrace CreateDebugTrace() => new DebugTrace();
```
with this:

```csharp
protected override IMvxTrace CreateDebugTrace() 
{
    var logger = new LoggerConfiguration()
                    .WriteTo.LiterateConsole()
                    .WriteTo.RollingFile("log-{Date}.txt")
                    .CreateLogger();

    return new MvxSerilogTrace(logger);
}
```

allow people to provide their own loggers. Simple and straight forward. <sup> though not enough in my opinion</sup>

# Proposal 2

The problems with approach number 1 are:

- When using Serilog, the `tag` parameter becomes pretty much useless, since they use their own DSL.
- We limit users to only a subset of the possible LogLevels provided by Serilog
- The general usage of `IMvxTrace` is a bit cumbersome (You either have to include an `using static` or use `MvxTraceLevel.TraceLevel`)

So what we could do is rethink the `IMvxTrace` interface completely to make it simpler to use:

- Add more `MvxTraceLevel`s so they match with Serilog better
- Add one method per LogLevel instead of allowing the user to provide the LogLevels*
- Possibly drop the `Tag` parameter  
- Add a notice on the default `IMvxTrace` that we ship with the StarterPack recommending users to check the Serilog version, for it allows much more flexibility (they can choose to ignore and use the default boring implementation, but that's on them).

My vote is for proposal number 2. I am willing to implement either (number 1 is pretty much completed, needing only some cleaning up) or discuss this further so we come to an agreement.
___ 
* We could keep the current methods with a deprecation notice and remove them for 6.0

**Comment by ghuntley** [comment]
My proposal is to not take hard dept on Serilog. If users want to use it then they can use it themselves. Create a separate opt-in package that plumbs IMvxTrace over to Serilog but srsly? It's a single class 💯 does it need to be a nuget package? It's pretty easy to implement :)

**Comment by ghuntley** [comment]
Second proposal: remove IMvxTrace and use https://github.com/damianh/LibLog for communicating framework logs to the developer; i.e. still encourage people to explore better options.

**Comment by Cheesebaron** [comment]
Not sure what I was thinking when I wrote the issue. (probably tired, drunk or just thought Serilog was awesome (which it is))

Taking a hard dependency on Serilog isn't great at all, adding another dependency you can't opt-out that not _everybody_ will use. If anything, we should probably just improve MvxTrace as needed for internal trace. If people want to bubble up messages from MvvmCross to Serilog, NLog, whatever log they can just implement IMvxTrace against those libs. We could look at LibLog to see if it adds any value for us.

**Comment by drungrin** [comment]
My proposal is the following, not using LibLog:

`            MvxSetup.UseApplication<MyMvxApplication>()
                    .UseTargetFactory<MyMvxBindingFactory1>()
                    .UseTargetFactory<MyMvxBindingFactory2>()
                    .UseDebugTrace<MvxSerilogTrace>()
                    .UseViewModelAssemblies(() => new[])
                    .Start();
`

I use actually NLog + LogEntries (for diagnostics) and InterCom + Twitter Answers for telemetry.

If you start using LogEntries, use my referral code :D [https://logentries.com/learnmore?code=a209b8c2]
