### ISSUE TITLE
Android : Exceptions in MvxValueConverter<TFrom, TTo>.Convert are hidden

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#1655]
When the Convert method of an implementation of MvxValueConverter throws an exception, no error is logged, and nothing appears in the log.

The crash is handled silently somehow.

It should log an error to the android log and to the Mvx.Error log instead.

**Comment by Cheesebaron** [comment]
It seems like all exceptions are caught and `MvxBindingConstant.UnsetValue` is returned. No logging.

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platform/Platform/Converters/MvxValueConverter.cs#L38

I guess we should use MvxBindingTrace here or MvxError to let the dev know, instead of just swallowing it.
