### ISSUE TITLE
PictureChooser.iOS scales incorrectly on high DPI devices

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#1759]
### Steps to reproduce
Take a picture with the picture chooser task on iOS with a pixel dimension larger than the `maxPixelDimension` (which should be passed), on a retina display that has a default scaling > 1.0. Save the picture somewhere - upload it or put it in the device photo album.

### Expected behavior
The maximum dimension of the picture should equal the passed `maxPixelDimension`

### Actual behavior
The maximum dimension equals `maxPixelDimension * s` where `s` is the device scaling factor.

### Configuration

**Version:** 4.x

**Platform:** iOS

### Cause
The code at line

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Plugins/PictureChooser/MvvmCross.Plugins.PictureChooser.iOS/UIImageHelpers.cs#L58

initialises an image context with the scaling factor set to 0, which means the default device scaling factor will be used for the image. The target image size however does not take this scaling factor into account. Therefore the resulting image's actual size will depend on the scaling factor of the device.

**Comment by ben-dean** [comment]
+1 on this issue.

I've noticed this myself today. I'm assuming that this is a bug as Android doesn't scale images based off the device's screen density.

My use case for the images, is uploading them to an API, so I'm getting inconstant image dimensions depending on the users device. The current code would make sense if I was just showing the image on screen and never uploading it.

**Comment by Cheesebaron** [comment]
If anyone wants to fix this I have marked it up for grabs.

**Comment by ben-dean** [comment]
It's a one character (3rd parameter on BeginImageContextWithOptions) change telling the image context not to automatically determine scaling.

It currently has 0 specified, which means it will look at the device and change the width and height based on the device. x2 for a retina device and x3 for a plus device. 

By specifying 1 it wont scale the width or height at all.

**Comment by Cheesebaron** [comment]
But if you don't use scaling factor to multiply the width and height, wouldn't that cancel it out?

**Comment by ben-dean** [comment]
The image.CurrentScale property is set to tell you if the image is designed for retina screens and the size property will always be set to the computed size rather than the actual size.

E.g.

| Actual Size | Filename | Size Property | CurrentScale Property |
| --- | --- | --- | --- |
| 100x100 | image.png | 100x100 | 1 |
| 200x200 | image@2x.png | 100x100 | 2 |
| 300x300 | image@3x.png | 100x100 | 3 |

The first part of the method is great for working out what the true size of the image is, size x scale.

Currently the second part will use a context with the target size and the screen scale of the current devices to produce a new image (by supplying a 0 value to the context).

E.g.

| Target Size | Screen Scale | Size Property | CurrentScale | Actual Size |
| --- | --- | --- | --- |
| 100x100 | 1 | 100x100 | 1 | 100x100 |
| 100x100 | 2 | 100x100 | 2 | 200x200 |
| 100x100 | 3 | 100x100 | 3 | 300x300 |

My pull request fixes the scale to 1 so that the actual size is always the target size.

E.g.

| Target Size |Screen Scale | Size Property | CurrentScale | Actual Size
| --- | --- | --- | --- |
| 100x100 | 1 | 100x100 | 1 | 100x100 |

I've made my change dependent on the fact that this is only used by the camera and library, which will always produce an starting image that has a scale of 1.  Therefore I shouldn't be scaled to the device's screen when resized. 

We could actually remove the usage of the CurrentScale from the first part in this case and assume it will always be 1 as the original size doesn't actually matter.

The Chafu link is great for if you are resizing an image to be shown on a device and you want to make sure it has the same effective size regardless if the device is a 6 (@2x) or 6+ (@3x). The actual size would be different but it would take the size amount of screen space as the size properties would report the same (because of CurrentScale being set to 2 or 3 on the relevant device).

**Comment by ben-dean** [comment]
If you do think it could be used with images created for display on screen with a CurrentScale specified, a new parameter on the method could be added so you can toggle whether the final resized image scales based on the device or not. 

Currently it always does, I think it shouldn't, but maybe a parameter would let the consumer decide.
