### ISSUE TITLE
Sqlite plugin no more ConnectionWithLock

### ISSUE THREAD

**Issue by Jerome2606** [MvvmCross/MvvmCross#1833]
### Steps to reproduce

1. Install last plugin sqlite

2. In IMvxSqliteConnectionFactory, there is no more GetConnectionWithLock available

### Expected behavior
GetConnectionWithLock should still be available (obsolete at least if this is not a good way to go)

### Actual behavior
No ConnectionWithLock available

### Configuration

**Version:** 4.4

**Platform:** iOS/Android/Windows UWP

**Comment by Cheesebaron** [comment]
SQLite plugin has been discontinued. It was just a stupid wrapper around other libraries. The method `GetConnectionWithLock` disappeared when we switched from SQLite.Net (Oystein Krogh) to sqlite-net-pcl (Frank Kreuger). Former does still not support Android N or newer, which is why we switched.

I am closing this issue. You can simply make a lock in your own implementation.

**Comment by Jerome2606** [comment]
@Cheesebaron 
I'm coming back to my implementation.
Can you point me to an example of using sqlite-net-pcl in mvvmCross plz ?

As I see on your website you are still explaining using factory or behind the Factory you are using sqlite-net-pcl ?
https://mvvmcross.github.io/mvvmcross-docs/documentation/plugins/sqlite-pcl/sqlite-pcl.html

Maybe you can guide me how to switch from previous implementation of plugin to the new one ?
Should I delete the plugin and make the injection of dependency directly on sqlite-net-pcl ??

Thanks

**Comment by Cheesebaron** [comment]
Official docs are here: https://www.mvvmcross.com/documentation/
