### ISSUE TITLE
Call Close immediately after receiving the return value by NavigationService, view(activity) cannot close itself.

### ISSUE THREAD

**Issue by jz5** [MvvmCross/MvvmCross#1851]
### Steps to reproduce

```c#
public class FooViewModel : MvxViewModelResult<string>
{
    private readonly IMvxNavigationService NavigationService;
    public FooViewModel(IMvxNavigationService navigation)
    {
        NavigationService = navigation;
    }
    public MvxAsyncCommand BarCommand => new MvxAsyncCommand(async () =>
    {
        var result = await NavigationService.Navigate<BarViewModel, string>();
        await Close(result); // iOS: can close this, Android: cannot close this
    });
}
```

### Expected behavior
Android also can close 
I want to close both views.

### Actual behavior
View of BarViewModel is closed.
View of FooViewModel isn't closed.

Activity is finished in MvxAndroidViewPresenter's Close method.
MvxAndroidViewPresenter.Activitiy(```Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity```) still refers to activity of BarViewModel when Close is called.
I have no solutions. Are there ideas or workarounds?

### Configuration

**Version:** 5.0

**Platform:** Android

**Comment by MrXemiu** [comment]
I've had a similar problem.  On Android with 'public class MainActivity : MvxCachingFragmentCompatActivity<MainViewModel>, INavigationActivity' as a hosting Activity and navigating between Fragments, what I've seen is that, using your example, `FooViewModel.Close(result)' navigates **back** to `BarViewModel`.

I, too, am searching for a solution which would allow me to chain `Close(result)` to pass data backwards.

**Comment by martijn00** [comment]
When using commands with the new navigation MvxAsyncCommand should be used.

**Comment by jz5** [comment]
It still doesn't work using MvxAsyncCommand on v5.0.1.
Minimum project: https://github.com/jz5/MvxApp1851

**Comment by nmilcoff** [comment]
The reproduction project doesn't use a custom presenter, therefore [this](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/MvxAndroidViewPresenter.cs) is the one being used. It looks like an issue with `IMvxAndroidCurrentTopActivity`, may be related to #783.

**Comment by rrispoli** [comment]
Hi, I'm using MvvmCross 5.2.1 and this problem is occurring with me. I have a ViewModelA that go to ViewModelB and then ViewModelC.

The ViewModelB wait the result of ViewModelC close and then close itself. The ViewModelB was closed, but in Android, the view/activity remains in the screen and the debug show this warning "Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel" (https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/MvxAndroidViewPresenter.cs#L569)

Maybe the proccess it's happening too fast in Android? Or I'm doing something wrong? 

On iOS it's fine.

The ViewModelA wait the result of ViewModelB close. Despite the screen shows the view/activity equivalent of ViewModelB, the code works.

I can "fix" that problem adding a "await Task.Delay(50)" before the close command on ViewModelB

This gist contains all the code: https://gist.github.com/rrispoli/3887282a9ef81f0b42fbeda74cdbd6d8

**Comment by eL-Prova** [comment]
We have similar but in iOS. ViewModel needs to be closed and event thrown. But the close is slow. Should Close not make itself awaitable?

**Comment by adli89** [comment]
> Hi, I'm using MvvmCross 5.2.1 and this problem is occurring with me. I have a ViewModelA that go to ViewModelB and then ViewModelC.
> 
> The ViewModelB wait the result of ViewModelC close and then close itself. The ViewModelB was closed, but in Android, the view/activity remains in the screen and the debug show this warning "Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel" (https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/MvxAndroidViewPresenter.cs#L569)
> 
> Maybe the proccess it's happening too fast in Android? Or I'm doing something wrong?
> 
> On iOS it's fine.
> 
> The ViewModelA wait the result of ViewModelB close. Despite the screen shows the view/activity equivalent of ViewModelB, the code works.
> 
> I can "fix" that problem adding a "await Task.Delay(50)" before the close command on ViewModelB
> 
> This gist contains all the code: https://gist.github.com/rrispoli/3887282a9ef81f0b42fbeda74cdbd6d8

I'm having exactly the same problem, but 3 years later, I'm on MvvmCross v6.4.2. The gist posted by @rrispoli is exactly how my situation is, and I managed to work around the issue by putting a short delay (on my testing phone I needed at least 250ms) before calling `Close`.

@martijn00 should I file a new issue for this, or is it sufficient to track it here?
