### ISSUE TITLE
Add a way to change presentation attribute of ViewController at runtime

### ISSUE THREAD

**Issue by ynovella** [MvvmCross/MvvmCross#1887]
It would be convenient to be able to override the `PresentationAttribute` of a `ViewController` before navigating to it.

For example an `MvxRootPresentation` ViewController could later be shown as an `MvxModalPresentation`.

This could maybe be achieved using the `MvxBundle` parameter.

### Configuration

**Version:** 5.x

**Platform:** 
- [x] iOS

**Comment by Cheesebaron** [comment]
Right now it is only possible to hint through Attributes that you want a view to be shown Modal. This way you can't change presentation mode at runtime for the VIew.

It would be neat to be able to switch how to present at runtime. It was kind of possible with the old Presenter, but overriding the presenter and sending a presentation bundle or change presentation prior. Not possible with the new.

**Comment by nmilcoff** [comment]
Does it make sense to create an overridable method in all iOS base view classes, that would let the view itself change the attribute in runtime? Or maybe an interface that the developer can implement

**Comment by mvanbeusekom** [comment]
I think we could indeed make an interface the developer could implement to override the attribute. The logic will by something like this:

- iOS View Presenter will check if interface is implemented;
- if so the presenter will cast the view controller to the interface and uses this instead of the attributes
- if not the presenter will use the attributes (which can also implement the interface keeping all subsequent logic the same)

if you like, I could make a PR

**Comment by nmilcoff** [comment]
That sounds great to me @mvanbeusekom 💯
