### ISSUE TITLE
Add generic interface for IMvxCommand

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1946]
We should add generic interfaces for `IMvxCommand` and `IMvxAsynxCommand` to be able to use the interface as type for the command. This would probably also enables us to provide compiler errors when types don't match and make the code a bit simpler.

**Comment by willsb** [comment]
Since `IMvxCommand<T>` implements `ICommand`, one would still be able to call `Execute(Object parameter)`, so type mismatches would still be possible. We could, however:

```csharp
    public interface IMvxCommand<T> : ICommand
    {
        [Obsolete("Use the strongly typed version of Execute instead", true)]
        new void Execute(object parameter);

        [Obsolete("Use the strongly typed version of CanExecute instead", true)]
        new bool CanExecute(object parameter);

        void RaiseCanExecuteChanged(T parameter);

        void Execute(T parameter);

        bool CanExecute(T parameter);
    }
```

This adds extra safety to the type, but I think this use of shadow is a bit gross. 
One can still, of course, cast the `MvxCommand<T>` to `ICommand`, but then it's not our fault anymore ¯\\ _ (ツ) _ /¯

I'm starting this discussing to see what other contributors think, because I wanna work on this feature

**Comment by martijn00** [comment]
@willsb Your suggestions look good. Can you open a PR?

**Comment by leye0** [comment]
How can I pass platform specific object to a ViewPresenter via a command if I can't use "object" as a type? Ex: I have UIPopover in my app, so when tapping on a button, I pass the UIButton as an object to my ViewPresenter as the original tapped view to make my Popover appearing at the proper location. I've always used that approach everywhere in my MvvmCross projects, but can't use it with the awaitable navigation feature.
