### ISSUE TITLE
MvxNavigationService never calls IMvxViewModelLocator.Load

### ISSUE THREAD

**Issue by alexyak** [MvvmCross/MvvmCross#2036]
When using MvxNavigationService to navigate to a ViewModel the custom implementation of the IMvxViewModelLocator never gets called.

### Steps to reproduce

1. Create a project that requires navigation between ViewModels and implements a custom IMvxViewModelLocator

2. Use MvxNavigationService to navigate to the second ViewModel

3. The Load method of the custom IMvxViewModelLocator never gets called.

### Expected behavior
The Load/Reload methods of the custom IMvxViewModelLocator should be called

### Actual behavior
The Load/Reload methods of the custom IMvxViewModelLocator never get called.

### Configuration

**Version:** 5.0.5

**Platform:** 
- [ x] iOS
- [ x] Android
- [x ] WPF
- [x ] UWP

**Comment by nmilcoff** [comment]
You are right. The new NavigationService has its own implementation of [LoadViewModel](https://github.com/MvvmCross/MvvmCross/blob/b551d59da19db55cfbdeb13b62fbe94c7a6dcadc/MvvmCross/Core/Core/Navigation/MvxNavigationService.cs#L175). I belive this is intended in order to avoid the deprecated CIRS lifecycle. But the problem is you can't use a custom ViewModelLocator, just as you describe. Maybe @martijn00 has something to add about this?

A workaround at the moment is to subclass the navigation service and override `LoadViewModel` method.

**Comment by biruto05** [comment]
I got the same problem.

In App.cs, if I use `RegisterAppStart<LoadingViewModel>();` then everything is fine.
However, when I create custom AppStart and use `Mvx.Resolve<INavigationService>().Navigate<LoadingViewModel>()`, then its constructor is called twice.

This happens for android only.
