### ISSUE TITLE
2 Factor Login required for the MvvmCross organization from 22 September

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2195]
We are enabling 2-FA login for the entire MvvmCross organization on 22 September. If you are not already using 2-FA login, I strongly advise you to enable it. When we make the switch, any person inside of a team of the organization, which does not have 2-FA enabled will automatically be removed. If you want to remain a member, enable 2-FA.

**Comment by tofutim** [comment]
2-FA is overhyped IMHO but ok, done.

**Comment by Cheesebaron** [comment]
Care to elaborate?

**Comment by tofutim** [comment]
Everyone is in a rush to get to any kind of 2-FA not because of security but because of liability. If a major company does not offer or enforce 2-FA, if there is a breach, then they have not "tried their best". Think about how FA is implemented on Github, through SMS.  What happens if I leave my cell phone at work, or run out of power, or AT&T has an outage, or I'm in a room with wifi but poor reception? What happens if I drop my phone and it breaks? I could be down for days!

I have a physical RSA key for corporate bank account access. Rain or shine it spins its magic codes. It works above ground or in my nuclear bunker (with hi-speed internet, of course). I can drop it from 10' and it won't break. It has calculator type display. Battery lasts 10 years. This makes sense - for a bank account. SMS, ugh... annoying and not so much.

I'm not against 2-FA. I'm against blind panic requiring everything to be 2-FA. Given today's litigious society, I know it is inevitable. But please allow a tiny bit of old man whining...

**Comment by mvanbeusekom** [comment]
@tofutim since you clearly don't own an Nokia 3210 I suggest you use the "authenticator application" option instead of SMS. This integrates great with 1password (and I am sure there are also other applications which do the job nicely). This will also work in you nuclear bunker as long as you have power (and if you don't I'd guess you won't be needing acces to GitHub anyways ;)).

**Comment by Cheesebaron** [comment]
YubiKey and Authy also works well. There a loads of alternatives to SMS.

**Comment by tofutim** [comment]
Actually I might have a 3210 somewhere..

**Comment by Cheesebaron** [comment]
@JohannesRudolph @benschi11 @steveydee82 @PeterBurke @jamsoft @csteeg @PaulLeman @mattwhetton @SeeD-Seifer @promontis @AlanYost @mohibsheth @ckimes89 @mgj @davidschwegler @tomgilder @ggirard07 @robertbaker @SlyNet @sescandell @tekkies @modplug @slown1 @roubachof @SimonSimCity @scastria @kiliman @PelleRavn @clintonrocksmith @nicolgit @spockfish @Ericslnl @royd @fedemkr @PerPage @zleao @chrilith @pauloapsantos @Prin53 @Nickolas- @g0rdan @ehuna @viniciusmaia @Costo @orzech85 @drungrin @alexeyn-martynov @svego @markverkiel @munkii @Garfield550 @LRP-sgravel @AnthonyNjuguna @eL-Prova @thongdoan @jhorv @tritter @biozal @ilber @Daniel-Krzyczkowski @domedellolio @DaRosenberg @jamespettigrew @HeMinzhang @bazookajoey @flyingxu @mellson @VenkatsQuest @jz5 @c-lamont @F1nZeR @wickedw @kkrzyz @daniel-varela @duglah @ryupold @ferrydeboer @senorincognito 

Are you guys OK with being vacated from the MvvmCross organization? If so don't do anything. If not, enable 2FA. Will give this another week *2nd October 2017* is the deadline.

**Comment by Cheesebaron** [comment]
@Garfield550 @LRP-sgravel @AnthonyNjuguna @eL-Prova @thongdoan @jhorv @tritter @biozal @ilber @Daniel-Krzyczkowski @domedellolio @DaRosenberg @jamespettigrew @HeMinzhang @bazookajoey @flyingxu @mellson @VenkatsQuest @jz5 @c-lamont @F1nZeR @wickedw @kkrzyz @daniel-varela @duglah @ryupold @ferrydeboer @senorincognito

**Comment by JohannesRudolph** [comment]
I haven't contributed in quite some time due to a shift of focus, feel free
to remove me from the organization. Thanks!

Am 25.09.2017 12:40 PM schrieb "Tomasz Cielecki" <notifications@github.com>:

**Comment by chrilith** [comment]
Hi,

Still have this PR to merge... have to find time. I enabled 2FA.

Bye

**Comment by ilber** [comment]
@Cheesebaron you can remove me for now. Will come back if I have to fix something. Thanks

**Comment by Cheesebaron** [comment]
Just to clarify, this does not disallow Pull Requests or seeing any information in any of the projects, except organization wide [projects](https://github.com/orgs/MvvmCross/projects) like the one we made for .NET Summer Hackfest. 
Most of the mentioned users are members of the Contributors read-only team, which is where they are going to be removed from if 2FA is not enabled.

**Comment by mohibsheth** [comment]
You can remove if required. I've enabled 2FA as well.

**Comment by drungrin** [comment]
Enabled as requested.

Enviado do seu iPhone

Em 25 de set de 2017, à(s) 12:07, mohibsheth <notifications@github.com> escreveu:

**Comment by biozal** [comment]
Done.

-Aaron

**Comment by Nickolas-** [comment]
Done. Just get a email , you need to do that previous , to notify everybody with emails.

**Comment by Daniel-Krzyczkowski** [comment]
2FA enabled.

**Comment by Cheesebaron** [comment]
@Nickolas- we could also just have enabled it and not much harm would have been done. People who are actually interested could just get added back to the organization after enabling 2FA.

**Comment by Prin53** [comment]
I have enabled 2FA.

**Comment by Nickolas-** [comment]
@Cheesebaron a lot of people on vacation right now , maybe they didn't know about that.

**Comment by Cheesebaron** [comment]
@Nickolas- even so, not much harm done, they can be re-added when they come back 😃

**Comment by eL-Prova** [comment]
Done, 2FA enabled

**Comment by flyingxu** [comment]
@Cheesebaron sorry I was on a trip. Now I enabed 2FA.

**Comment by kjeremy** [comment]
:rocket:

**Comment by DaRosenberg** [comment]
@Cheesebaron Done!

**Comment by domedellolio** [comment]
@Cheesebaron  2FA enabled

**Comment by PelleRavn** [comment]
All done 👍  A good opportunity to get it enabled

**Comment by thongdoan** [comment]
@Cheesebaron I have enabled 2FA

**Comment by HeMinzhang** [comment]
@Cheesebaron I have enabled 2FA.

**Comment by PeterBurke** [comment]
I now have two factor authentication for GitHub. Thanks.

**Comment by modplug** [comment]
I now have two factor authentication for GitHub. Thanks.

**Comment by Garfield550** [comment]
@Cheesebaron Enabled 😄

**Comment by sylvain-toptal** [comment]
Done
