### ISSUE TITLE
MvxSettings usage?

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2204]
Hi, are there any samples that show how to use MvxSettings? In particular binding UI items to the Settings, or am I thinking about this incorrectly? I do see the CreateSettings in Setup.cs.

**Comment by fedemkr** [comment]
I'm not sure what you need to do but `MvxSettings` exists so that you can configure `AlwaysRaiseInpcOnUserInterfaceThread ` (currently) which indicates whether you want the `RaisePropertyChanged` (from `MvxNotifyPropertyChanged`) to be executed always on the user interface thread as well as the `RaiseCanExecuteChanged` of a command. This setting can be configured in the Setup -> CreateSettings (by default `AlwaysRaiseInpcOnUserInterfaceThread ` is `true`)

[Here](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/ViewModels/MvxNotifyPropertyChanged.cs#L39) MvxNotifyPropertyChanged gets configured by that setting and [here ](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/ViewModels/MvxNotifyPropertyChanged.cs#L69) it is used.

[Here](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/ViewModels/MvxCommand.cs#L116) MvxCommandBase gets configured by that setting and [here](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/ViewModels/MvxCommand.cs#L136) it is used.

Hope it helps.

**Comment by Cheesebaron** [comment]
Closing this. OP please ask on SO or Slack.
