### ISSUE TITLE
C# The type or namespace 'Core' could not be found. CS0246

### ISSUE THREAD

**Issue by montecillodavidacn** [MvvmCross/MvvmCross#2210]
Im using VisualStudio 2017 Community Edition. 
Im starting out to develop Xamarin.Native using MVVMCross. 

AS I started it out It seems I encountered a bug that I dont understand.
`
    C# The type or namespace 'Core' could not be found. CS0246`

Im watching this [video-tutorials-mvvm-starterpack](https://www.youtube.com/watch?v=NihmK6R9r4s&lc=z22mxpc4vkeohd2s5acdp431wh0ftp55wghrr3vix2xw03c010c.1505738364088460)

I followed the instructions carefully and encountered the bug and I even tried to fix the bug which is stated [here](https://stackoverflow.com/a/14532490) still nothing happened.

So this is where the issue occurs in `Setup.cs` under my Xamarin.Android.
```c#
    using Android.Content;
    using MvvmCross.Droid.Platform;
    using MvvmCross.Core.ViewModels;
    using MvvmCross.Platform.Platform;
    
    namespace MVVMApp1.Droid
    {
        public class Setup : MvxAndroidSetup
        {
            public Setup(Context applicationContext) : base(applicationContext)
            {
            }
    
            protected override IMvxApplication CreateApp()
            {
                return new Core.App(); // here problem lies the Core 
            }
    
            protected override IMvxTrace CreateDebugTrace()
            {
                return new DebugTrace();
            }
        }
    }
```

**PS: I posted this on SO, So now kindly guide me to the right direction.** [C# The type or namespace 'Core' could not be found. CS0246](https://stackoverflow.com/q/46292254/8630750)

**Comment by mvanbeusekom** [comment]
Hi @montecillodavidacn, 

The line that is causing the problem is trying to instantiate the `App` class which is located in the shared (or core) project. In this case the `Core` refers to the namespace core project containing the shared code if the app. There could be a view things wrong here:

1. Make sure you reference your core project from your Android and iOS projects;
2. Check the namespace of the `App` class inside your core project. MvvmCross StarterPack assumes it is called `<YourAppName>.Core` (in your case `MVVMApp1.Core`). If you used a different name, simply update the call to `Core.App();` to contain the correct namespace (note that you also include the correct using statement and still make sure the project is referenced, see point 1).

Hope this helps. If you have more questions don't hesitate to ask.
