### ISSUE TITLE
Initialize is not called

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2212]
If I use "ShowViewModel<TViewModel>" the "Initialize" method is not called (Xamarin.Forms).

**Comment by mvanbeusekom** [comment]
That is correct and is expected behaviour. The `Initialize` method is called only when using the `NavigationService.Navigate` method. When using the `ShowViewModel` method you'll have to use the `Init` method. More information can be found here: https://www.mvvmcross.com/documentation/fundamentals/navigation

**Comment by CarLoOSX** [comment]
What about a tabs application ? Thank you!
