### ISSUE TITLE
MvxCollectionViewController and xib - "... view outlet was not set"

### ISSUE THREAD

**Issue by Cybrosys** [MvvmCross/MvvmCross#2230]
### Steps to reproduce

Create a View controller that inherits from `MvxCollectionViewController<SomeViewModel>`, so a .xib is also created.

Open the .xib and make sure that the file owner and view controller point to the view controller you just created.

1. Call `ShowViewModel<SomeViewModel>()`

### Expected behavior
View controller is shown using the .xib.

### Actual behavior
constructor with IntPtr handle is missing. After adding that, I get the below error instead:
`-[UIViewController _loadViewFromNibNamed:bundle:] loaded the "SomeViewController" nib but the view outlet was not set.
`
If I remove the .xib, everything works; but I want to use the xib.

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Are you using IB or Xamarin Designer? (I had [a problem](https://bugzilla.xamarin.com/show_bug.cgi?id=58198) with IB and outlets yesterday)

**Comment by Cybrosys** [comment]
@nmilcoff Xamarin in Visual Studio on Windows

**Comment by cfl777** [comment]
I had similar issues on VS for Mac, despite it working in the past. But when I created the xib using:
`new project-> View Controller` instead of `new project -> View` it just worked. 
Seems like if you manually try to connect a xib to a class it breaks, even though nothing different between past projects to the new one in the way I created them. 

[This is an answer similar](https://stackoverflow.com/questions/45052836/loading-a-xib-using-mvvmcross-and-xamarin), but for VS for windows.
