### ISSUE TITLE
Attempting to install Xamarin.Android.Support.Exif into iOS project

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#2272]
The Nuget packages to version 5.3.0 appear to be broken.

When updating from version 5.2.1 the installer will attempt to install Xamarin.Android.Support.Exif into  PCL-libraries and into iOS projects.

Could not install package 'Xamarin.Android.Support.Exif 25.3.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Plac3hold3r** [comment]
The issue is related to the PictureChooser Plugin having a dependency on `Xamarin.Android.Support.Exif 25.3.1` . I have submitted a pull request to resolve this #2273.

**Comment by alexsorokoletov** [comment]
Please update the NuGet package, guys! @Plac3hold3r thank you for fixing this small glitch ;)

**Comment by ElteHupkes** [comment]
FYI the plugin might not install right now even if you try it with `Ignore-Dependencies`, because the PCL component targets a different profile than the rest of MvvmCross:

https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/MvvmCross.Plugin.PictureChooser.nuspec#L27
`target="lib\portable-net45+win+wpa81"`

vs. for instance

https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/MvvmCross.Core.nuspec#L21
`target="lib\portable-net45+win+wpa81+wp80"`
