### ISSUE TITLE
How to use the IMvxOverridePresentationAttribute when nothing's available?

### ISSUE THREAD

**Issue by Cybrosys** [MvvmCross/MvvmCross#2340]
I get the idea of the IMvxOverridePresentationAttribute interface, but the main issue I'm having is that no data/information is available when the method is invoked.

My problem is that I want to reuse a storyboard and view controller, but in one case it should be presented as a Tab, and in another case it's just supposed to be presented normaly. So I thought I'd check the parent view controller type to determine if the method should return a MvxTabPresentationAttribute or not. But it's null, everything is null.

Maybe the method should get some information/context as to who/what requests it?

**Comment by nmilcoff** [comment]
Maybe @mvanbeusekom can shed some light on this?

**Comment by mvanbeusekom** [comment]
I recognize your complaint, when I created the interface it looked like a nice way to hook into the live cycle of the presenter when processing the presentation attributes. However since the processing of the attribute is happening before the related view model is constructed, it is impossible to send it to the supplied implementation of the `IMvxOverridePresentationAttribute`. 

We can however have a look if it is possible to send the instance of the view controller to the interface implementation. This might give you something to work with (although very fragile since the related view model will still not be there).

**Comment by Cybrosys** [comment]
What I've done in the meantime is make the state I'm interested in available statically (TabBarController is active), so I can return the `MvxTabPresentationAttribute` when needed.

**Comment by nmilcoff** [comment]
> We can however have a look if it is possible to send the instance of the view controller to the interface implementation. This might give you something to work with (although very fragile since the related view model will still not be there).

The interface implementation is, in the 99,999% of the cases, the ViewController itself, so this won't be really helpful in most scenarios.

BUT, a thing we could do is to send the `presentationBundle` (or the MvxViewModelRequest itself) over to the `PresentationAttribute` method. We'll need to change some bits of the ViewPresenters to support this, but it's definitely possible.
