### ISSUE TITLE
[Android] New activity not started if first fragment is registered with current activity

### ISSUE THREAD

**Issue by dlpopescumtk** [MvvmCross/MvvmCross#2402]
### Steps to reproduce :scroll:

1. Register _FirstFragment_ with _ActivityOne_ and _ActivityTwo_, from the _MvxFragmentPresentation_ attribute
2. Start _ActivityOne_ by calling _Navigate(ActivityOneViewModel)_
3. From _ActivityOne_, call _Navigate(FragmentOneViewModel)_

### Expected behavior :thinking:
Normal MvvmCross behaviour would be to start _ActivityTwo_ and bring up _FragmentOne_. 

### Actual behavior :bug:
_ActivityOne_ brings _FragmentOne_ into view.  Workaround is to _Navigate(ActivityTwoViewModel)_ and, then, to _FragmentOneViewModel_. Any way we could change the fragment presentation attribute at runtime?

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is expected behavior. MvvmCross doesn't magically know which `Activity` you want to use, so if it is other than the one you are on, and other than the first `Attribute` declared, you have to navigate to it yourself first.

You could use the `IMvxOverridePresentation` interface to determine which `Activity` to use on runtime.

**Comment by dlpopescumtk** [comment]
@martijn00 , thank you!
