### ISSUE TITLE
Fragments inside ViewPager are not restored 

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#2403]
This is a clean version of #2287.

### Steps to reproduce :scroll:

1. Run Playground.Droid 

2. Navigate to TabsRootView

3. Rotate device

### Expected behavior :thinking:
Fragments inside ViewPager should be recreated.

### Actual behavior :bug:
Fragments inside ViewPager are not recreated. This happens when using `MvxTabLayoutPresentationAttribute` and `MvxViewPagerFragmentPresentationAttribute`

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
The more I try to solve this issue, the more I think the best we could do is to just remove the PresentationAttributes for ViewPager / TabLayout and let users configure ViewPager and TabLayout by theirselves... Not only ViewPager is a complicated widget by design (and the `ViewPager.Adapter` could be anything that inherits `PagerAdapter`...), but also Activities and Fragments add some extra levels of complexity because of their lifecycle.

The only downside I can see for removing them, is that on iOS when you're using tabs you can do MvxNavigationService.Navigate<MyTabViewModel> and let the Presenter do the magic for you. The attributes are handy on this situation.

**Comment by nmilcoff** [comment]
Alright, I did some more testing today and found out that the issue isn't related to the way we display ViewPager fragments (which is really good). 

Only Playground.Droid had the issue and it was solved by adding the flags: `ConfigurationChanges = Android.Content.PM.ConfigChanges.Orientation | Android.Content.PM.ConfigChanges.ScreenSize` on `TabsRootView`.

I'll open a PR to fix that in the repo.

**Comment by yanxiaodi** [comment]
The `ConfigurationChanges` cannot handel all the scenarios. Please see this issue: https://stackoverflow.com/questions/21554419/android-androidconfigchanges-value-for-font-style-change-in-samsung-device
When the user changes the font-family or font-weight for Samsung phones, `ConfigurationChanges` cannot handle it because it is not the standard API from here: https://developer.android.com/guide/topics/manifest/activity-element#config
So the tabs is lost again.
Can we reopen this issue? Thanks.
