### ISSUE TITLE
Question: Is there a way to actively dispose pages and viewmodels?

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2433]
I hope this is the right place for asking question too. Is there any way with MvvmCross.Forms to dispose pages and view models which are no longer in the navigation stack? If I navigate quick enough in one of my applications (which contains a bunch of maps), I receive a MemoryWarning from the iOS system. I already try to dispose as much as possible and call `GC.Collect()` actively, but it seems it is not enough because the old pages and viewmodels seems to be still in the memory. Is there any way to access them and trigger the dispose? Or is there something else I can do, to free up the memory from old navigations? 

I try to analyze it as much as possible, and so far it seems the memory usage is growing with each navigation but does not really shrink (tested with Xamarin.Profiler).

**Comment by nickrandolph** [comment]
@Sebastian1989101 I'm guessing that this isn't specific to MvvmCross and that it's XForms that's probably maintaining references to the old pages and not freeing them up quick enough. Are you certain that you don't have references to the pages/viewmodels that aren't being cleaned up. For example if you're referencing a messaging service, or similar, make sure you've unsubscribed, otherwise the reference will keep the viewmodel, and most likely the page, alive.

**Comment by Sebastian1989101** [comment]
@nickrandolph Thanks for the advice. I really found two places where the events stays alive and now it seems to work a bit better (at least I need todo the same thing about twice at often before it crashes). Maybe I should review my code for stuff like this.

**Comment by nmilcoff** [comment]
GitHub is for issues only, please use StackOverflow, Xamarin Forums or Slack for questions.

Also as @nickrandolph says, I don't think this is MvvmCross related. ViewModels are attached to Views and live as long as the View is alive.
