### ISSUE TITLE
Broken navigation after a modal view navigates to a MvxRoot view

### ISSUE THREAD

**Issue by BjarneFisker** [MvvmCross/MvvmCross#2503]
### Steps to reproduce :scroll:

1. Download test project at: https://github.com/BjarneFisker/CloseModalTest

2. Click on "Show Modal View"

3. Click on "Navigate to root view"

4. Click on "Show Modal View"

5. Click on "Navigate to root view"

6. The app is now broken and no further navigation is possible to any views

I know that a simple "Close" on the modal view would be a workaround in the test example. But in my case the modal view is quite more complex and features multiple navigations/subviews within the modal view. A "Close" would only pop the last view in the modal navigation controller. I need to close all views inside the modal view.

### Expected behavior :thinking:
It should still be possible to open the Modal view or navigate to any other view in the app

### Actual behavior :bug:
Navigation requests are ignored. Buttons and commands are still fired, but no exception is presented.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by PelleRavn** [comment]
Might be something @nmilcoff knows about?

**Comment by nmilcoff** [comment]
I just gave the sample a quick look and it seems to me you're trying to close the RootViewController of the window, but you want to close the modal navigation stack instead. You should close `ModalViewModel` [here](https://github.com/BjarneFisker/CloseModalTest/blob/master/CloseModalTest.Core/ViewModels/ModalViewModel.cs#L37) instead of `FirstViewModel`.

Suppose you have a child ViewController displayed inside the modal navigation stack. If you do `Close<ModalViewModel>` it will close the entire modal nav stack, which is what I think you're after.
