### ISSUE TITLE
OnCreate is called after first ContentPage

### ISSUE THREAD

**Issue by kciesiel** [MvvmCross/MvvmCross#2549]
### Steps to reproduce :scroll:

1. Add extended component (FFImageLoading or GrialKit (it is not free))

2. Set initialization in OnCreate()
CachedImageRenderer.Init(true);
or
GrialKit.Init(this, GrialLicenseResourceName);

3. Create custom styles in FormsApp.xaml which use those components
4. Use these styles in first ContentPage
5. Run the app

### Expected behavior :thinking:
It works correctly

### Actual behavior :bug:
Exception: {FFImageLoading/GrialKit} is not initialized. 
**Reason**: In MvvmCross 5.6 case OnCreate is called after FormsApp and first ContentPage

### Configuration :wrench:

**Version:** 5.6

**Platform:** 
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms
- [ ] :iphone: iOS (not sure)

**Comment by nmilcoff** [comment]
Did you try to initialize those services on the Setup class?

**Comment by kciesiel** [comment]
It is impossible. It has to be in onCreate().

**Comment by borbmizzet** [comment]
This has been a problem for me too.   I'm currently migrating a project to MvvmCross from Vanilla Xamarin.Forms, and we have a splash screen style which is set as the Theme for the Activity Attribute for MainActivity, then we change the theme to the main style at the beginning of MainActivity.OnCreate().  We do this in order to keep the application to a single activity in order to allow external Intent to launch the MainActivity (which doesn't work when using MvxSplashScreenActivity) as well as propagate through while it is already running.  I get a blank NavigationPage because the ContentPage is created before changing the theme.

**Comment by nickrandolph** [comment]
@kciesiel can you please check to see if this issue is still present (we've changed a lot of the start up behaviour for Mvvmcross and need to know if this issue is still present). Perhaps if you can repro using the playground sample (develop branch) and PR your changes.
