### ISSUE TITLE
MvvmCross.Plugin.Location.Fused 5.6.3 is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by marcfeldman** [MvvmCross/MvvmCross#2607]
Hi,
I'm still a complete newbie to MvvmCross, so apologies in advance if this is the wrong 'forum'.
As suggested, I have posted to SO and Xamarin as well.

### Steps to reproduce :scroll:
1. Start with a VS 2017 Solution for Android, using MvvmCross 5.6.3 and netstandard 2.0 as the Target Framework.

2. Using NuGet Manager for the Core project, add MvvmCross.Plugin.Location.Fused 5.6.3.

### Expected behavior :thinking:
It should work.

### Actual behavior :bug:
Package MvvmCross.Plugin.Location.Fused 5.6.3 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package MvvmCross.Plugin.Location.Fused 5.6.3 supports: monoandroid (MonoAndroid,Version=v0.0)

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
It is a Android class library. You can't add those to Net Standard projects.

**Comment by marcfeldman** [comment]
Hi,
Thank you for the very fast response time.  That really helps.
1.  When you say "Android" class library, what does that mean?
     I thought MvvmCross was a cross-platform framework, not Android specific?
2.  I can install MvvmCross.Plugin.Location 5.6.3.
3.  Where does each plugin 'advertise' its compatibility?
4.  If I want the benefits of 'fused' location, what are my choices?
     I understand, perhaps incorrectly, that the net "standard" was introduced specifically for 
     "small' devices like phones?
     Can I change my project to "regular" .NET?  What version?
Thank you,
Marc

**Comment by Cheesebaron** [comment]
So for the Fused plugin to work you need to:

1. Add MvvmCross.Plugin.Location to your core and other projects you might want to use it (except Android)
2. Add MvvmCross.Plugin.Location.Fused to your Android project
3. Make sure step 2. added a Bootstrap file registering the Fused location plugin

As for your questions:

1. You are right for the most part. However, some things, like plugins cannot be cross-platform as they contain platform specific things. So this is handled by having a interface + platform specific implementation(s) that are injected at runtime. For plugins these are typically registered through a Bootstrap file
2. Yes, but that NuGet contains more assemblies, for different targets
3. Typically you can look at the `Dependencies` section for a specific NuGet: https://www.nuget.org/packages/MvvmCross.Plugin.Location.Fused/
4. See my answer above

Hope this helps 😄

**Comment by marcfeldman** [comment]
Hi,
It is definitely helping to get my thinking straightened out.   :-)  
Is this an example of the "bait and switch" design paradigm?  
Coming from years of server-side Java programming, the overall environment is so different.  
Is it correct to think of Mono like a Java Virtual Machine, providing an execution environment for the CLR produced by the C# compiler?
Thx,
M.

**Comment by marcfeldman** [comment]
Hi Martijn,
I see you opened #2607 for 6.0.  
Other than fixing the thinking in my head, what problem did you detect with the plugin?
"Cheesebaron" implies it it working as designed, if I just knew how to use it properly?
Thx,
M.

**Comment by marcfeldman** [comment]
Hello Cheesebaron,
Just like MvvmCross is convention based, much of my education is convention based: I look at the examples and try to generalize to my code.
Above you said: "Make sure step 2. added a Bootstrap file registering the **Fused** location plugin".
When I look at N-09 I see:
`: MvxPluginBootstrapAction<Cirrious.MvvmCross.Plugins.Messenger.PluginLoader>`
and
`: MvxPluginBootstrapAction<Cirrious.MvvmCross.Plugins.Location.PluginLoader>`
The file in my project has:
`: MvxPluginBootstrapAction<MvvmCross.Plugins.Location.Droid.Plugin>`

Question:
Is the change from `PluginLoader` to just `Plugin` a part of the evolution of the framework, or am I doing something wrong?

Thx,
M.

**Comment by Cheesebaron** [comment]
No this is not bait and switch. This is Inversion of Control, where MvvmCross used (obsolete in 6.0.0) bootstrap files to register which implementation to use of a plugin at runtime.

Is mono a VM, yes CLR is the runtime, so you probably mean the Common Intermediate Language (CIL), this is what is executed in the runtime and compiled by the compiler. Although, I think it is a bit out of scope of this issue 😄 

This plugin will simply have its dependencies updated for 6.0.0, so the Google Play Services will be updated.

Your bootstrap will need to look like:

    : MvxPluginBootstrapAction<MvvmCross.Plugins.Location.Fused.Droid.Plugin>

This will pick up the `Plugin` class from the fused location plugin namespace rather than the other.

**Comment by marcfeldman** [comment]
Hello again,
Thank you for your continued support.
Which API should I be coding against?
You said:
-  "Add MvvmCross.Plugin.Location to your core".
-  "Add MvvmCross.Plugin.Location.Fused to your Android project"
The NuGet blurb clearly states that ...Fused provides an implementation of the `FusedLocationApi`.
So far, all my code has been in the Core project (Services and ViewModels), but the Core project only has the pre-Fused (standard) Location API?  No?  Yes?

1.   I think I understand that at execution time **all** the code will be executed by Mono on my Samsung S4 under the Android OS?
2.  The basic premise of Xamarin and MvvmCross is that the "Core" logic can also be deployed to run under iOS?
3.  I write the application logic that actually uses the lat and lon in the Model section of the Core project?
4.  I move the current code that interacts with the FusedLocationApi into the .Droid project?  Are there any "best practices" regarding folder names and/or class names?
5.  I use Messaging to send 'pure' lat/lon data from the platform-specific code to the cross-platform "Core' code?  Loose coupling?

Does any of that rambling make sense?

Thx,
M.

**Comment by Cheesebaron** [comment]
The NuGet `MvvmCross.Plugin.Location` consists of the following targets

- _pcl_ - provides `IMvxLocationWatcher` and some helper classes and models
- _xamarin.ios_ - implementation of `IMvxLocationWatcher` for iOS
- _xamarin.android_ - implementation of `IMvxLocationWatcher` for Android
- _uap_ - Windows UWP implementation of `IMvxLocationWatcher`
- _wpf_ - WPF implementation of `IMvxLocationWatcher`

Now there is something called Fused Location Provider on Android which comes from the Google Play Services. To no impose the restriction of having to reference those services we provide a separate implementation of `IMvxLocationWatcher` which uses this provider.

So instead of registering the implementation of `IMvxLocationWatcher` for Android from `MvvmCross.Plugin.Location`, you add `MvvmCross.Plugin.Location.Fused` to your Android project and register that instead. So that implementation will be used instead.

So bullet point 2, yes.

1. mono may call into Android classes and vice-versa, but generally, yes
2. yes
3. yes
4. don't know what you mean, you will probably never interact with with the Fused Location Provider yourself. You will only see the `IMvxLocationWatcher` in your core. Call folders what makes sense to you.
5. You will still just use the `IMvxLocationWatcher` interface, actual implementation is chosen at runtime based on what is registered.

If you have more non-MvvmCross related questions, I highly suggest you sign up for Xamarin University or some Plurasight courses. These questions are beginning to be way out of scope of what we have time and want to answer.
