### ISSUE TITLE
Soft back button in Android when using DrawerMenu

### ISSUE THREAD

**Issue by closetoyou293** [MvvmCross/MvvmCross#2690]
### Steps to reproduce :scroll:

1.Clone XPlatformMenus project and update to latest MvvmCross version
Link in github [https://github.com/closetoyou293/HambugerSample]()
2. Back button does not show when navigate to second view.
3. Change code: always call below line of code in base fragment, back button shows:
`mainActivity.SupportActionBar?.SetDisplayHomeAsUpEnabled(true);`

### Expected behavior :thinking:
Soft back button should work.

### Actual behavior :bug:
There is nothing happen when click on back button on navigation bar, hard back button works.

### Configuration :wrench:

**Version:** latest from nuget

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Please open an issue on the MvvmCross-Samples repository instead of here.

I'd guess it's something wrong on the Android views setup rather than a problem with MvvmCross... If you could help us bump XPlatformMenus to latest and greatest, that would help us get it resolved! (seems you already have done part of the migration :) ).
