### ISSUE TITLE
Resource.Layout' does not contain a definition for '[ViewName]'

### ISSUE THREAD

**Issue by younas-bangash** [MvvmCross/MvvmCross#2801]
```
namespace SampleApp.Droid
{
    [Activity(
      MainLauncher = true,
      NoHistory = true,
      ScreenOrientation = ScreenOrientation.Portrait)]

    public class SplashView : MvxSplashScreenActivity
    {

        public SplashView()
           : base(Resource.Layout.View_Splash)
        {
        }
    }
}


```

 

### Steps to reproduce :scroll:
Just follow the video
https://www.youtube.com/watch?v=NihmK6R9r4s
1.

2.

3.

### Expected behavior :thinking:
Tell us what should happen
it should work as just shown in the video
### Actual behavior :bug:
Tell us what happens instead

it show the following error
Resource.Layout' does not contain a definition for '[ViewName]'
### Configuration :wrench:

**Version:** 5.7

**Platform:** 

Android

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by younas-bangash** [comment]
What information you want to know on your website you just specify the video I follow the same video but its not working nor your documentation is properly written

**Comment by Cheesebaron** [comment]
This is an open source project, If you do not feel like our documentation is up to par with your expectations, I highly suggest you find an alternative that does so or start contributing. We have limited resources and none of us are technical writers. Be happy that we at least have _some_ documentation.

The code is distributed under the MS-PL license, which guarantees nothing.

The video you refer to is for MvvmCross 4 and hasn't been updated to a newer version.

You issue sounds like you are either:
1. Missing a NuGet package
2. Just need to rebuild your project
3. Using an outdated version of Visual Studio

Since you are providing very limited information about what you are trying to do and didn't provide a repro sample, then we have very limited means of helping you.

If you want to get started with MvvmCross, I suggest you take a look at one of our sample projects, like our [StarWars sample](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/StarWarsSample) or our [Playground sample](https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground) and work your way from there.
We do plan on making the beginner experience better, but all this takes time. Most of us do this in our spare time without being paid anything for this.

**Comment by younas-bangash** [comment]
@Cheesebaron ok thanks a lot for your clarifications.
