### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by scotch83** [MvvmCross/MvvmCross#2806]
**Request for MvvmCross Reference documentation**

Hello, 

it would be nice **if possible** to have a reference of the framework like a standard language reference. 

Like this:
https://developer.android.com/reference/android/Manifest.permission.html
With all the classes and methods and related descriptions and use.

Thank you

**Comment by younas-bangash** [comment]
one of the best platform and it have worst documentation mostly their webpages are down

**Comment by Cheesebaron** [comment]
@younas-bangash your comment isn't appreciated. Instead of going from issue to issue and flaming us, I suggest you leave constructive criticism instead. I.e. it would be better to point out which exact part is down or is unclear.

**Comment by nickrandolph** [comment]
@Cheesebaron well said - I'm going to close this issue as we already have documentation as a TODO.
@younas-bangash we're always looking for volunteers - please submit PRs to include appropriate documentation instead of raising issues with thing you'd like to see
@scotch83 we're always conscious of the need for documentation but there is a massive trade off between documentation and implementing features and bugs. As you can see from the commit history the bulk of the work is done by only a few people. We'd love more assistance in the form of PRs rather than issues outlining a wishlis of features.

**Comment by younas-bangash** [comment]
@Cheesebaron accept my apology if my comment is not proper my point is not to criticise anyone, you do a nice job I just point out that what you mention in the video is not working that's it and I raised that issue #2801.

**Comment by scotch83** [comment]
sorry guys, the last I meant to raise was such a storm. I got the answer to
open the issue from someone on the slack channel. I would not even think
about it as an issue, actually, but rather a todo. Btw did you consider and
documentation generator able to create at least a skeleton?
Thank you for taking your time on this anyhow. it s a great framework and
you have all my respect. Greets and have a nice day everyone!

Mattia Collalti

**Comment by nickrandolph** [comment]
@scotch83 there's no problem creating the issue so that we have something to track requests for documentation against (even if we then close the issue). As @Cheesebaron mentioned we need to be careful about adding more maintenance (usually what happens with generators) which just won't happen. 
Take for example we'd all love to have complete test coverage, and so the question becomes: are we adding more value by writing documentation, fixing bugs, adding features or writing tests. Usually bug fixing wins in nearly every case.
We'd love for the community to contribute back by adding documentation they find useful.

**Comment by scotch83** [comment]
Good point! Have a good day ahead all!

Mattia Collalti
