### ISSUE TITLE
[Droid Forms] OnAppearing / OnDisappearing not called on first child of MvxTabbedPage

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2823]
### Steps to reproduce :scroll:

1. Using MvxTabbedPage with multiple MvxContentPages 

2. Use OnAppearing / OnDisappearing on a child page of the TabbedPage

### Expected behavior :thinking:
Should be called.

### Actual behavior :bug:
Is only called if I switch the tabs but not for the first page. 

### Configuration :wrench:

**Version:** 6.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by mkieres** [comment]
I'm experiencing similar issues. 

The problem seems to be related to the timing of the navigation to the tabs. In the Playground sample for the tabs page, navigation to the the MixedNavTab1ViewModel and MixedNavTab2ViewModel is happening in the ViewAppearing of the root TabbedPage (in the MixedNavTabsViewModel). This works fine i.e. the OnAppearing on the tab pages is being called - at least in my app, which is using almost exactly the same code as in the sample. However, when you add a slight delay before navigating to the tabs, then the things go south. 

Unfortunately I cannot build the MvvmCross source code and run the Playground sample myself to demonstrate this (I'm getting build errors), but I would imagine that adding Task.Delay() should showcase the problem. The code that should cause this behaviour could be located in the MixedNavTabsViewModel and could look something like this:

        private async Task ShowInitialViewModels()
        {
               await Task.Delay(100); 

                var tasks = new List<Task>();
                tasks.Add(NavigationService.Navigate<MixedNavTab1ViewModel>());
                tasks.Add(NavigationService.Navigate<MixedNavTab2ViewModel>());
                await Task.WhenAll(tasks);       
        }

Just to confirm what @Sebastian1989101 wrote, the OnAppearing is indeed being called once you switch between tabs.

Affected Version: 6.2.0

**Comment by mkieres** [comment]
I think this problem might actually be related to the Xamarin.Forms issue https://github.com/xamarin/Xamarin.Forms/issues/3855
