### ISSUE TITLE
Memory leak on opening browser and returning back on droid

### ISSUE THREAD

**Issue by aoershov** [MvvmCross/MvvmCross#2884]
https://github.com/aoershov/MvvmCrossMemoryLeakBrowser

I add logs to MvxMultipleViewModelCache to see memory leak:
https://github.com/aoershov/MvvmCrossMemoryLeakBrowser/blob/master/MvxMultipleViewModelCacheWithLogs.cs

### Steps to reproduce :scroll:

1. Press "Open second view"
2. Press "Open browser"
3. Browser is shown
4. Press back

### Expected behavior :thinking:
No memory leak.

### Actual behavior :bug:
From logs I see than FirstViewModel and SecondViewModel added to cache on opening browser,
but never cleaned on back press.
This problem is serious for us because we call Dispose of view model on back press. So we get disposed view model from cache on second opening SecondViewModel. 

 

### Configuration :wrench:

**Version:** 5.7

**Platform:** 
- [x] :robot: Android

**Comment by nickrandolph** [comment]
Can you please reproduce this:
a) on v6.0.1 (latest stable)
b) in the playground
If you can reproduce this in the playground sample, can you submit the repro as a PR for us to investigate further

**Comment by aoershov** [comment]
We can reproduce issue on 6.01
Pull request is
https://github.com/MvvmCross/MvvmCross/pull/2888

**Comment by nmilcoff** [comment]
I'll try to take a look at this one over the weekend, I've worked on that viewmodel cache before

**Comment by nmilcoff** [comment]
Alright so the problem is quite old... Proper support for fragments was introduced in #771 this was a concern back then (hint: search for `MvxMultipleViewModelCache` in the comments).

We need to add a way to clear ViewModels from `MvxMultipleViewModelCache`. Changing the `ConcurrentDictionary` for a `ConditionalWeakTable` or wrapping the ViewModel objects on `WeakReference`s won't do the work, because we want to keep strong references there (if the tombstoning process is activated, `MvxMultipleViewModelCache` is the only place where the ViewModels will be kept alive).

The only thing I can think of is to attach a listener for fragment operations or hook into a method and modify the cache from there. Maybe someone else has a better idea?

**Comment by nmilcoff** [comment]
I think I've found a solution. PR is on it's way!
