### ISSUE TITLE
Allow ResX key names to comply with naming guideline when using ResXLocalization 

### ISSUE THREAD

**Issue by dastbayoo** [MvvmCross/MvvmCross#3109]
## 🏗 Enhancement Proposal

The [naming guideline for ResX resources](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-resources) recommends to only use alphanumeric characters and underscores. However, MvxResxTextProvider relies on the dot (.) as a separator, which is not compliant. It would be great if the separator could be configured (in order not to introduce a breaking change) and eventually favour "_" as the default separator.
![Example of Compiler Warning](https://user-images.githubusercontent.com/43368060/45672449-76bd3f00-bb28-11e8-935b-eec59485386a.png)

### Pitch

Complying with the naming convention would eliminate compiler warnings. Ultimately, the dot is replaced with "_" when generating the .Designer.cs class anyway, so the change could also reduce confusion between code and resource key name.

**Comment by StevenBonePgh** [comment]
This is a duplicate of #2926 which I added. I am waiting for a response from the maintainers as how it should be fixed, and proposed several options, including yours, based on the level of breaking change they are tolerant of. I would gladly submit a pull request, but I don't wish to do it more than once, hence the query.

**Comment by dastbayoo** [comment]
I am sorry that I failed to see there already was an issue for this. I am not sure I understand your comment: Are you asking whether we might both be submitting a pull request?

**Comment by StevenBonePgh** [comment]
I'm saying I won't be submitting a pull request until I get a response from the maintainers as to how they wish it to be fixed, as it can be fixed with varying levels of breaking changes. I'm hesitant to submit breaking changes without maintainer buy-in first. I worked around it by deriving from `MvxResxTextProvider` and overriding `GetText` and `TryGetText` since they are fortunately virtual. I needed to add some other functionality anyway (like getting localized text for an enum), so I already was deriving from it. When fixed in MvvmCross I could remove those overrides, but it is not blocking me at all.

**Comment by dastbayoo** [comment]
Okay, thanks for clarifying and even providing an advice for a workaround. I was just unclear whether you were implying I should take some kind of action. I guess I'll just mark it as duplicate.

**Comment by dastbayoo** [comment]
Duplicate of #2926.

**Comment by dastbayoo** [comment]
Well, the marking kinda didn't work.
