### ISSUE TITLE
Development on Mac, can't build the projects

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross#3210]
## 🐛 Bug Report

It seems that the mvvmcross.sln can't be build on a Mac with Visual Studio for mac IDE.
but I see some issues related to mac like #3156, he seems to be able to build and run. I'm curious how should I develop (build and debug) on a mac?
Any workaround or build by command line?

### Expected behavior
mvvmcross.sln can be opened by Visual Studio for Mac and the playground projects should be able to build and debug.

### Reproduction steps
Can't build any of the project
![screen shot 2018-11-22 at 16 12 42](https://user-images.githubusercontent.com/122225/48890088-cb57a000-ee72-11e8-8135-8c3234bd0012.png)

### Configuration
Visual Studio for Mac, latest version

**Version:** 6.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Visual Studio for Mac _still_ after 2 years does not have proper support for Multi-Targeting.

Also currently there seems to be a bug in SourceLink where LibGit2Sharp fails because it can't load some dll's, on mac.

We can unfortunately not do much about this.

**Comment by projectgoav** [comment]
Stumbled across your issue here when looking for something else. If I remember correctly, this was how I was able to get Mvx to build on a Mac.

- Ensure you have the latest VS for Mac installed on your machine.
- Ensure you have **ALL** of the Xamarin platform SDKs installed (Xamarin Mac, Xamarin iOS and Xamarin Android). I think you *may* need to have a version of the Android build tools installed and *possibly* an android SDK as well which tripped me up. They can be installed as part of the VS installer or using the SDK manager that's available from the VS for Mac menus. I can't remember exactly

    **You will need to install all of the SDKs even if you don't plan on that platform. The cake script doesn't do any detection on the SDK availablility and will crash out without them.**

- Remove the `SourceLink` reference from the `directory.props` file. See comment here: https://github.com/MvvmCross/MvvmCross/issues/3145#issuecomment-427083513

- From the command-line run Nuget restore (I had to run it twice for it to pick up everything. My Mac was doing [weird and wonderful things](https://github.com/MvvmCross/MvvmCross/issues/3155) when I did this so you might not experience this)
- Run the cake script to build the MvvmCross libraries to make nuget packages etc. 
- Open the MvvmCross solution and select the playground app you want to run
- Hit *Build* or the play icon to start it running
   **Don't use *Rebuild* as VS Mac will try and rebuild the MvvmCross project which it can't do**

I may have tried to edit the playground solution to reference the `bin/debug` output of MvvmCross rather than the project directly but can't remember if this was successful or not. 

You will only be able to use iOS or Android apps should you wish to use the remote build/debug from Windows wih VS2017. Microsoft don't support, and probably never will, that feature for Mac apps.

**Comment by flyingxu** [comment]
I would elaborate a little bit:

1) Remove the SourceLink reference

2) run `nuget restore MvvmCross.sln` in cmd

3) run cake script
install cake: `brew install cake`
then in the MvvmCross.sln folder, run `cake`


Everything seems to be ok but when I open the sln in VSMac and run, I got

>Error: Configuration 'Debug|iPhoneSimulator' not found in project 'MvvmCross' (MvvmCross)

**Comment by projectgoav** [comment]
You'll need to select a playground project you want to run and set it as the startup project first!

**Comment by flyingxu** [comment]
Yes I did, see my screenshot
![screen shot 2018-11-28 at 8 07 05 pm](https://user-images.githubusercontent.com/122225/49150909-3b6d9680-f349-11e8-95fb-ab3e87a4113f.png)

**Comment by projectgoav** [comment]
This rings a bell....

I think this was when I started going down different routes. If you disable/unload the MvvmCross project and rely on the Cake script to build it, VS for Mac might ignore it when building the playground. 

If not this where I removed the reference to it and manually added all the DLLs as references.....
