### ISSUE TITLE
Sources compilation

### ISSUE THREAD

**Issue by cristianvasuica** [MvvmCross/MvvmCross#3232]
Could somebody from the team please give some hints on how to get the source code compiling?
After installing some dependencies (UAP, Tizen Sdk), I am stuck in some errors related to DependencyObject, DependencyProperty not found errors - image attached below.
I have to mention that I want to directly reference the MvvmCross in order to have a better understanding in what the framework does beneath the hood, especially NavigationService.Close which gives a nasty error with leaked window in an Android app which shows an activity with a popup theme.

Ps: Many thanks for this great framework!
![image](https://user-images.githubusercontent.com/18456488/49942140-279b6600-feed-11e8-9010-e28099b8449f.png)

**Comment by nickrandolph** [comment]
The source code in the master and develop branches should compile without error. Please make sure you running the latest release of Visual Studio. Also, due to limitations with multi-targeting, compilation on VS for Mac is not currently supported.
I'm going to close this ticket - please direct further questions to stackoverflow or the slack channel.
