### ISSUE TITLE
Search Bar in Title (Forms)

### ISSUE THREAD

**Issue by SebastianKruseWago** [MvvmCross/MvvmCross#3325]
## 💬 Questions and Help

The last time I checked this, it was not supported. But before I start one project and build it to the point I need to test it, I thought I ask first: Is there any support for SearchBar within the title bar? I know this is a feature for iOS and Android but here is a example post for iOS: https://blog.xamarin.com/add-search-bar-xamarin-ios-11/ 

In iOS this is for example used in the native settings app while Android use this for example in the YouTube app. 

I'm not sure if this is supported, how it needs to be added with MvvmCross.Forms. Do I need to do it with custom renderers? Is there any built in mechanic?

**Comment by Cheesebaron** [comment]
If you can do it with Xamarin.Forms, you can probably do it with MvvmCross too. We don't do anything to hold you back.

**Comment by Sebastian1989101** [comment]
> If you can do it with Xamarin.Forms, you can probably do it with MvvmCross too. We don't do anything to hold you back.

Dosn't stuff like this require to create a own NavigationPage? For stuff like this you need full control over the NavigationPage (or at least the NavigationBar in it). Is there any example how to use a own custom NavigationPage within a MasterDetail navigation while using MvvmCross? Because as soon as I set "WrapInNavigationPage = true" in my MvxMasterDetailPagePresentation, MvvmCross does all of this for me and hides this from me. I can't find anything in the documentation neither how I can specifiy which navigation page is used for this wrapping.
