### ISSUE TITLE
Remove UWP support?

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#3341]
## 🏗 Enhancement Proposal

Remove UWP target platform from list of supported platform.

### Pitch

It seems like most people don't really care about UWP support. My suggestion is to remove support for this platform, to have one less platform to have to maintain.

Nothing new from Microsoft for UWP for a long time and I don't hear much about people making UWP Apps. Ever since Windows Phone was discontinued nothing much has been going on. Asking other developers, their main reason to use UWP is to simply quickly debug their Apps, instead of having to run a Android Emulator or iOS Sim.

What do you think?

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Decline ;-)  The main reason I'm a big advocate for MvvmCross over other frameworks like Prism is that we have support for all the platforms. If we start to selectively remove them, it degrades the value of the framework considerably.

**Comment by cornelha** [comment]
I might not be a contributor, but I use this daily. My main mobile application uses UWP for Windows support.

**Comment by JTOne123** [comment]
I'm using for UWP, all my MvvmCross.UWP apps are in the MS store, works great! Thank you guys, MvvmCross is great.

**Comment by Cheesebaron** [comment]
Thanks for the feedback. I just wanted to vent this, since there was some discussion about this at the MVP summit between Framework devs.

**Comment by JTOne123** [comment]
Play this game https://bubbles-game.printslon.com (based on mvvmcross 6.3.0) and relieve your hate windows stress and love UWP as I do :)

**Comment by dansiegel** [comment]
@nickrandolph keep in mind here, that OSS Maintainers have a responsibility to themselves and their platforms first. While you might like that a particular library supports UWP the simple fact of the matter is there has to be a reason for Maintainers to want to support a platform. Sometimes this may be personal development interests, but more likely it is that a particular platform helps to drive their work life. 

Too often the community has unrealistic expectations of "deserving" something. If a project's maintainers do not have a reason to pour their efforts into a platform, and members of the community who rely on the platform do not step up and take ownership then you should expect to see MVVMCross among others following Prism's example of dropping UWP.

> I might not be a contributor, but I use this daily. -@cornelha 

I do not mean this to seem like an attack but rather food for thought for all of the OSS software you consume daily. OSS Maintainers hear this a lot. We appreciate it. We love that you find our projects helpful to delivering your solutions. Consider though, that when you use an OSS Library, but you do not contribute, and you do not offer serious financial support to the project then you should also understand that the needs of the maintainers outweigh your own needs.

**Comment by brianlagunas** [comment]
I would add that posting issues like these really won't give you the data you are seeking. The very few number of people that actually use UWP will definitely object as their projects rely on your continuous unpaid labor to support them.  Looking at the number of total PRs of around 1600, only abut 20 of them were for UWP. So that's about 1%. Of your total of 1800 issues, roughly 30 if them are UWP related. So about anther 1%.  Assuming we follow the same percentages for your total downloads of 1 million downloads gives you about 10K total downloads for UWP (including updates). Given the very low usage numbers, the lack of community contributions, the lack of innovation on the platform by MS, the lack of attention of the platform by MS, you have to ask yourself if you want to continue supporting it.

I wish you luck in making this decision, but remember this is about what's best for you and your team. It has nothing to do about what the "community" wants.

**Comment by nickrandolph** [comment]
@dansiegel - agreed with all points and definitely there was no disrespect intended to Prism in my comment (we use just as much Prism in my day job as we do MvvmCross). I definitely wouldn't be asking for continued UWP support if I wasn't a Maintainer, or at least willing to contribute to ensure continued support.

@brianlagunas - I understand your point about UWP devs looking for unpaid support but at least it might give us some indication of interest (ie better than none) and potentially an opportunity to engage some more developers to contribute. 
The flip side to your numbers is the amount of effort required to continue to support UWP. At the moment that effort is very low, so continuing to support is something we can do easily. If UWP becomes a problem-child, we can always come back to this decision and change it at that point. Dropping UWP now, would make it very hard to reintroduce support down the line.

**Comment by AlanYost** [comment]
Decline - we have a large client base in Western Australia that use our product that runs on UWP.  We would drop Mvx (or never upgrade) if it no longer supports UWP.  I'm with you all the way on this @nickrandolph

**Comment by brianlagunas** [comment]
@Cheesebaron Since everyone is saying how easy it is to support and they all depend on your project and your support so much, you can rest easy and know they will immediately start taking on the currently open 10 or so UWP issues and submitting PR's to help sustain the platform they so desperately need. Never mind the fact that you have UWP issues open since 2017. Better late than never I say.  Oh, and I bet since their businesses actually rely on your project to deliver value to their customers, they will start providing you some monetary support.

**Comment by dansiegel** [comment]
@nickrandolph no disrespect taken. Both Prism and MvvmCross fill specific needs, and I'm happy to hear that you're able to use each one where it makes the most sense. I also recognize that you have contributed to this project quite a bit... remember though there is a real difference in having the Contributor badge and Member badge. A contributor can walk away at any time, a Member has taken ownership of a project. So here's the real question... are you willing to jump on the grenade and take ownership for the UWP platform? Or are you only willing to commit to doing a PR here or there and demand that Core team continues to support you on something that may be a losing proposition for them? Also keep in mind that on an issue like this you're really only likely to hear from the couple of people using the Platform... for the 99% of people who don't care you're unlikely to hear from any of them.

@AlanYost you've made two PR's to this project one small one in 2014 the other 5-1/2 months ago changing 3 lines of code. You need to understand while that's great that you've contributed that isn't the same as maintaining a project. You're not going to like hearing this, but this isn't about you, or what you need for your business, and you certainly have not earned a right to demand that others work at their expense for free to help your business. This is about what's right for the core team that's actually responsible for maintaining the project. If MvvmCross is really so important to your business then why don't you consider making an annual $50,000 contribution to the core team to show your support. Give them a reason to support your business needs.

For all of you who **do not** have that Member badge next to your name, please take a step back and understand that the behavior of the .NET community with regards to .NET OSS Maintainers has led projects to be abandoned, and many maintainers to come to a breaking point. Before you respond `Decline`, ask yourselves if this or any other OSS Project is really vital to your business, what are you willing to do to support it? Are you willing to regularly help submit PR's and bring that issue count down to 0? Are you willing support it financially and I don't mean with $1 here or $20 there... Make a real commitment donate $10,000, $20,000, $50,000, $100,000 to show the maintainers that there hard work isn't going unnoticed and that it's driving real value. We know that many of you may work for smaller Indie shops where $50 or $100 would be a lot of money, but some of you also work for major Enterprises that make Millions every year because of projects like this one and the simple fact is that if you tried to develop your own version and maintain it yourselves you'd outspend that donation in wages probably in the first month.

@Cheesebaron this decision really is for you and your core team to make together outside of a GitHub issue. If someone like @nickrandolph wants to step up and take ownership, I'd certainly encourage you to take that into consideration, but hold their feet to the fire. If the core team would prefer to drop it in the absence of that support, make it clear that you'll drop it if you don't see it being maintained.

**Comment by brianlagunas** [comment]
@Plac3hold3r This is great, and it aligns well with the comment "Asking other developers, their main reason to use UWP is to simply quickly debug their Apps, instead of having to run a Android Emulator or iOS Sim"

May I ask what you are using to gather this data in the templates? AppInsights or other?

**Comment by Plac3hold3r** [comment]
@brianlagunas yip, AppInsights. The data is from users that have not opted out of Visual Studio telematary data capture. 

One point to add this is only data from Windows Visual Studio user. I unfortunate don't have sight in to users of the dotnet template generated projects.

**Comment by nickrandolph** [comment]
@dansiegel / @brianlagunas I understand that you both talk from a lot of well respected contribution to the OSS community. However, I think you might want to check some of the attitude you're bringing to this discussion and perhaps be slightly more conscious that you don't always know everything, particularly about a project you're not an active contributor on.

As an OSS project, everyone is entitled to their opinion on a public issue like this one, particularly where the whole point of the issue was to get feedback from the community. To have a go at them for how little they may have contributed is punishing them for expressing an opinion - this is just as bad as developers who make demands on Maintainers which contributing themselves.

@dansiegel as an FYI I am a core member and will continue to contribute so long as it matches my other life commitments. If the the other core members feel I'm not contributing enough I understand if I am moved back to just being a contributor. Having said that, even as a core member I don't feel I'd be doing the project justice if I didn't listen to all opinions, and then weigh them up against their contribution to the project.

I actually do work for @AlanYost and so what you don't see is that a lot of my contributions come as a direct result of seeing pain points they have encountered. This has the net effect that @AlanYost hasn't needed to contribute as much as might be warranted. My point is that contribution stats don't always paint a full picture.

@brianlagunas in an ideal world we'd be able to close all issues - the UWP issues are still open because we recognise there is a limit to the effort we as contributors can make, and that we expect developers who need those fixes to contribute. We keep them open to track the issues, rather than simply close them because they aren't high enough priority for us to fix at the moment. Currently when we add features/work on MvvmCross, UWP isn't causing us issues - this is my point from before. Why should we drop support for it, when it's not currently costing us effort to maintain support. The minute it does, then we can consider dropping it.

@brianlagunas / @dansiegel  I do, as I said before, value your opinions and contribution. I do feel that you're jumping in with a very loud voice on a project you're not an active contributor on. I appreciate the points you've made but I feel that you've taken this issue off topic and used it to drive the point that developers should contribute more to projects they use (a point I agree with but isn't the point of this issue). Feel free to DM me on Twitter as would love to work closer with you guys.

**Comment by brianlagunas** [comment]
@nickrandolph Looking back at my statements, I couldn't find anything that indicated that "I know everything", so I think that is an unfair personal shot at me. I tried to bring a different perspective to the conversation than just "I use it, so I need you to support it" point of view. I tried to provide data points based off the data within your own issues and PRs, and combine that with my own experience with this exact same issue.

I am also trying to provide support to @Cheesebaron from the perspective of a fellow OSS project owner. My points support the fact that the UWP community is not participating in any of the currently open issues and haven't for awhile, but instead relying on the project maintainers to support it solely. Yes, I did exaggerate that fact and as you pointed out, this is actually a much broader issue in the OSS community in general and is way off topic. I apologize for that.

With everything said, I still stand by my original statement:
"I wish you luck in making this decision, but remember this is about what's best for you and your team."

I don't want to hijack this thread, so it might be best to delete my comments.

**Comment by slodge** [comment]
Glad to see the discussions happening here.

It's good to ask the question about whether support is still needed.

It's good to listen to the answers too, and to open up about where more
contributions might help.

I've nothing but <3 and admiration for all the work the contributors and
users continue to do here. I've learnt heaps from so many of you.

Good work. Keep thinking. Keep talking.... And make sure you keep a good
sense of humour too - good laughs are worth more than their weight in
dollars :)



PS I still miss silverlight... maybe blazor will bring it back :)

**Comment by slodge** [comment]
Oh... And I was working on a 9 year old prism app this afternoon. Still
works and the code is really modular... And I got paid to work on it... so
thanks for prism too :)

**Comment by Cheesebaron** [comment]
Thank you for all the input! Every answer here is valuable, and I appreciate you all took the time to participate in the discussion.

We've already discussed this matter internally in the team, yesterday on a call, but I wanted to hear what the community has to say as well.

Personally I don't mind keeping UWP support as long as it doesn't hurt the rest of the code base, which it currently does not. Although, we know it has a couple of issues, that could use solving. So as long as it doesn't need a big amount of work to keep going, I guess we could keep it around. As soon as we feel it becomes a burden and no one wants to maintain it, we could phase it out.

Either way, we will talk more internally and make a final decision, on what to do. All of your answers will be taken into consideration.

Thank you for the support @dansiegel and @brianlagunas!

**Comment by andrechi1** [comment]
UWP is not used for ignorance. But It's the best choice for touch Windows applications.

**Comment by albertofustinoni** [comment]
Not only for touch apps: if you want an app that has some guarantees for end users (file system sandboxing, permissions, clean uninstall) UWP is the only way to do it.

Please do not remove UWP support: I have made 8 UWP apps that I regularly use and that were built with MVVMCross.
