### ISSUE TITLE
MvxAppStart class causing app freeze - wrong async pattern

### ISSUE THREAD

**Issue by arek-avanade** [MvvmCross/MvvmCross#3395]
## 🐛 Bug Report

When app starts, MvxAppStart class executes the following dirty line of code:
`StartAsync(hint).GetAwaiter().GetResult();`
`StartAsync` method indirectly calls the initial view model's `Task Initialize()` method. When the `Initialize()` method actually contains any async code (e.g. calls web service), this creates a deadlock, since main UI thread is blocked waiting on .GetResult() call in MvxAppStart and async/await code cannot resume after the web request back on the main thread.

### Expected behavior
App should not freeze. Async and blocking code should never be mixed.

### Reproduction steps
As provided above.

### Configuration

**Version:** 6.2.3

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by justinwojo** [comment]
This should be by design. If you read [this doc on customizing AppStart](https://www.mvvmcross.com/documentation/advanced/customizing-appstart), it specifically says to run any Tasks synchronously (such as a web API call). I don't necessarily like the approach, but it works fine if you just wait on the Result synchronously. We've been burned by this a few times, but always solved by making it synchronous.

**Comment by arek-avanade** [comment]
Honestly that sample doesn’t look good as well in terms of async best practices. That would be acceptable if this doesn’t have an impact on the consuming code, but in this case I need to change my view model, which knows nothing about the AppStart, just so that the app can boot up. And then my view model would also not follow async/await best practices.

Have you guys considered choosing a different approach to fix this?

**Comment by nickrandolph** [comment]
As background on this it's not that we aren't aware that we're forcing sync behaviour, it's that the various platform require synchronous startup behaviour. The issue is that the navigation model has Initialize as an async method to allow for long running actions to be done before navigation happens.... this doesn't work on app startup where the behaviour needs to be synchronous.
There are two approaches we could have gone with fixing this:
1) have a different navigation flow for startup - this was disregarded as we'd end up with a LOT of duplicated code and the experience wouldn't be great for developers trying to grok the framework
2) we fix the startup navigation to convert the async Initialize method into being run synchronously. This is non trivial and what's currently there is a stepping stone to the final result. Yes, currently it requires developers to be aware of this issue and NOT do async actions in the Initialize method on your first View Model (tbh you should avoid this anyhow but I understand there are times when this is unavoidable). 
There is work being done to fix (2) - see https://github.com/MvvmCross/MvvmCross/pull/3222
Feel free to contribute - reach out to @Cheesebaron if you have suggestions or want to contribute your time to fixing this issue.

**Comment by arek-avanade** [comment]
Interesting read. I think there is a much easier solution which enforces awareness about the start up process. I’ll post it in that thread in that case.

**Comment by casas333** [comment]
As a workaround to be able to have async code in the Initialize() method of the first view model you can register your custom app start class in App.cs

`RegisterCustomAppStart<CustomAppStart<AppAsyncViewModel>>();`

And in the CustomAppStart class do the following:

    protected override async Task NavigateToFirstViewModel(object hint)
        {
            var devicePlatform = DeviceInfo.Platform;
            if (devicePlatform == DevicePlatform.iOS)
            {
#pragma warning disable CS1998
                _ = NavigationService.Navigate<AppAsyncViewModel, object>(hint);
            }
            else if (devicePlatform == DevicePlatform.Android)
            {
                await NavigationService.Navigate<AppAsyncViewModel, object>(hint);
            }
        }

In the first view model's Initalize() method you can safely use standard async best practices:

`public override async Task Initialize()
        {
            if (_appSyncrhronizer != null)
            {
                IsBusy = true;
                _appSyncrhronizer.SyncFinish += Syncnronizer_SyncFinish;
                await _appSyncrhronizer.StartupSync();
            }
            
            await base.Initialize();
        }`
