### ISSUE TITLE
[6.3] 'MvxRecyclerAdapter.GetItemViewType' method returns wrong value

### ISSUE THREAD

**Issue by behzad62** [MvvmCross/MvvmCross#3404]
## 🐛 Bug Report

In the current version (6.3) 'MvxRecyclerAdapter.GetItemViewType' method for some reason  returns the value of 'GetItemLayoutId'  whereas in the previous versions it was returning the value of 'GetItemViewType'  method in the ItemTemplateSelector. Hence, it is either a breaking change or a bug.

### Expected behavior
It should return the value of 'GetItemViewType' method in the 'ItemTemplateSelector'.
### Configuration

**Version:** 6.3

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I guess you are referring to: https://github.com/MvvmCross/MvvmCross/commit/b6d4996254160d895d2af9e6170488c5ed710052?diff=split#diff-1484c3c6aea55b629a387ed8d4a7e28cR144

@softlion can you enlighten us why this was added. I missed this when testing and reviewing, but the code seemed to work.

Fortunately to work around this you can override the method in your own adapter:

```csharp
public override int GetItemViewType(int position)
{
     var itemAtPosition = GetItem(position);
     return ItemTemplateSelector.GetItemViewType(itemAtPosition);
}
```

**Comment by softlion** [comment]
GetItemViewType must return a unique value throughout the whole application, whatever the recyclerview is. Because the recyclerview does not destroy its viewholders after being destroyed, but return them to a pool instead. This pool is common to the whole app, and all recyclerviews try to reuse viewholders from it.

Returning a view type which is not unique leads to unexpected behavior, especially memory leaks or crashes. An index starting at 0 for each template set is not unique. So instead, now mvvmcross returns a layout id which is unique throughout the application and leads to a stable RecyclerView.

**Comment by Cheesebaron** [comment]
Sure, but this should be up to the MvxTemplateSelector implementation to decide what behavior is there. So previous behavior was to let the MvxTemplateSelector just return whatever is in its `GetItemViewType` for that position. Of course allowing the dev to return the wrong thing. Instead of returning a unique id for each view type you are going to show in the RecyclerView

Your change protects the dev, from doing bad stuff.

I will think about whether we should keep it as is or whether we should revert this behavior and document our way out of it.

**Comment by behzad62** [comment]
Well in my case, I used a custom 'SpanSizeLookup' in my GridLayoutManager to have some specific items (like headers) span through the RecyclerView width while other items only take one column:

        public override int GetSpanSize(int position)
        {
            switch (_adapter.GetItemViewType(position))
            {
                case 'header item':
                    return _spanCount;
                default:
                    return 1;
            }
        }
Fixing this was not much of an issue for me, Although, I don't think that a public method of the adaptor which itself is public property of RecyclerView should only be called by the RecyclerView.

On the one hand, since 'GetItemViewType' is a virtual method of the MvvmCross implementation of the RecyclerView.Adaptor, you are free to return whatever value you deem it appropriate.

One the other hand, deciding to use a shared pool for all RecyclerViews in the app is up to the devs and this change will not protect them if they use one item_template in two or more RecyclerViews or have a TempleteSelector which returns a common layout id for more than one RecyclerView in the app.

**Comment by Cheesebaron** [comment]
> On the one hand, since 'GetItemViewType' is a virtual method of the MvvmCross implementation of the RecyclerView.Adaptor, you are free to return whatever value you deem it appropriate.

Not correct, it is a method coming from RecyclerView.Adapter, we don't mark it virtual. We do, however, override it and return a value from the MvxTemplateSelector . You are free to return whatever value in your implementation. But if you are reusing view types in your MvxTemplateSelector for unrelated views you will have a bad time in some cases.

The MvxTemplateSelector is mimicking the RecyclerView.Adapter methods and is a way for you to provide what should be shown as part of the RecyclerView, without having to implement your own RecyclerView.Adapter.

Let's just agree this is a breaking change.
