### ISSUE TITLE
WPF View lifetime does not handle app closing

### ISSUE THREAD

**Issue by MartinZikmund** [MvvmCross/MvvmCross#3481]
## 🐛 Bug Report

When app is closed with the close button, the `ViewDisappearing`, `ViewDisappeared` and `ViewDestroyed` lifecycle events are not fired.

### Expected behavior

When app is closed with the close button, the `ViewDisappearing`, `ViewDisappeared` and `ViewDestroyed` lifecycle events are fired.

### Reproduction steps

Override any of the "disappearing" view lifecycle methods in view model and close WPF app. Observe the method is not called.

The reason for this behavior is that WPF does not call the `Unloaded` event on the Window. It is a known issue of WPF (which might be fixed now that it is open-source) but there are no clear plans for that yet.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by MartinZikmund** [comment]
I can take care of fixing this.

**Comment by martijn00** [comment]
@MartinZikmund Happy to review a PR for this.

**Comment by MartinZikmund** [comment]
Finally getting to it, hope to get the PR ready soon :-)

**Comment by snechaev** [comment]
Looks like this is still a problem in 9.0.10 in case when using `MvxContentPresentation` inside the main window.

### Steps to reproduce:
* Grab TipCalc sample
* Make sure that the `MvxContentPresentation` attribute is set for the `TipView` class and that the `TipView` itself is inherited from a `MvxWpfView` (and not `MvxWindow`).
* Override `ViewDestroy` in the `TipViewModel` and set breakpoint/logging there.
* Run the app
* Close the app with the red close window button.

### Expected
`TipViewModel.ViewDestroy` called.

### Actual
`TipViewModel.ViewDestroy` not called.

## Additional information
The cause is exactly the same - the `Unloaded` event is not fired for the last window *and all controls within that window*.

The fix provided by @MartinZikmund is works on the window level and calls `ViewDestroy` for the view model of the *window*. But in the case when `MvxContentPresentation` is used, the `MvxWindow.ViewModel==null`, and `MvxWindow.Content` is set to the `MvxWpfView` object which has its `MvxWpfView.ViewModel` set to the appropriate view model instance.
So, in the case of  `MvxContentPresentation` we need to do something like the following to access the view model (`this` is assumed to be `MvxWindow`)
```
if (this.Content is MvxWpfView { DataContext: MvxViewModel subVm})
{
    subVm.ViewDestroy();
    //other VM handling
}
```
Of course, the exact way in which the ViewModel is accessed will depend on the presenter, and the custom presenter may introduce a more complicated visual tree around the view object.

## Possible fixes
I have thought about the possible fixes, but found none without serious drawbacks. I will write them all down and maybe someone will be able to improve them or to provide a better solution.
* Extend `MvxWindow.Unload()` to traverse the whole visual tree and examine each element if it is a `MvxWpfView` then call `ViewDestroy()` on corresponding view models. The problem here is that the window will work with the elements without any knowledge of the structure and potentially may break something. Or it should request the structure information from somewhere (from the presenter?), so the windows will have additional (and weird) dependency.
* Move such a functionality to the `IMvxWpfViewPresenter` implementation. This way the presenter is responsible for keeping track of which view is placed in which window. And then when the window is closed (the presenter should subscribe to the corresponding event), the presenter should call the `vm.ViewDestroy()`. And the same thing when the view is removed from the window. This looks a little bit strange to me to add such a responsibility to the presenter and I'm also not sure if there is a case exists where the view can appear/disappear/destroy without direct help from the presenter. If there is, then we can't *move* the functionality from `MvxWindow/MvxWpfView` into the presenter, we can only *duplicate* the functionality into the presenter to handle the one special case.
