### ISSUE TITLE
Using MvxBindableListView makes Commands pointing on Models instead of ViewModels

### ISSUE THREAD

**Issue by hugoterelle** [MvvmCross/MvvmCross#35]
Hi Stuart, 

As discussed on stackoverflow (http://stackoverflow.com/questions/12682082/mvvmcross-changing-viewmodel-within-a-mvxbindablelistview), here is my point of view on the ideal axml file:

articles_view.axml

```
   ...
          <Mvx.MvxBindableListView
                android:id="@+id/listviewArticle"
                android:choiceMode="singleChoice"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:orientation="vertical" 
                local:MvxItemTemplate="@layout/article_rowlayout"
                local:MvxBind="{'ItemsSource':{'Path':'Articles'}}" />    
   ...


And here is the "article_rowlayout.axml"

   ...
            <TextView
                android:id="@+id/rowArticleLabel"
                android:layout_width="0dip"
                android:layout_weight="14"
                android:layout_height="wrap_content"
                android:textSize="28dip"
                local:MvxBind="{'Text':{'Path':'Item.Label'}}" />
            <ImageButton
                android:src="@drawable/ic_modify"
                android:layout_width="0dip"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:id="@+id/rowArticleButtonModify"
                android:background="@null" 
                android:focusable="false"
                android:clickable="true"    
                local:MvxBind="{'Click':{'Path':'MyCommand'}}"
              />
   ...
```

The "Item" word should be a "reserved word" pointing to the "Artcicles[x]"
And without "Wrapper" programming, the "article_rowlayout.axml" should always point on the ViewModel of the MvxBindableListView instead of working in the "Articles[x]" context.  

Another point of view should be to choose the viewmodel of the MvxBindableListView in the parameters: 

```
   ...
          <Mvx.MvxBindableListView
                android:id="@+id/listviewArticle"
                android:choiceMode="singleChoice"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:orientation="vertical" 

                local:MvxViewModel="xxx"

                local:MvxItemTemplate="@layout/article_rowlayout"
                local:MvxBind="{'ItemsSource':{'Path':'Articles'}}" />    
   ...

```

Where "xxx" should be the class we would like to use, or maybe a reserved word telling to use the current viewmodel (the one of the MvxBindableListView). 

Other points of view should be nice ...  

Hugo Terelle

**Comment by sescandell** [comment]
Hi there,

I also went into this issue (calling a command into the ViewModel from a click on a item template list). But I solved it in a different manner than a wrapper, and I think it is a better one speaking about isolation and domain model. I used the IMvxMessenger and custom Views. This was possible in my situation because creating a custom View makes sense. Maybe that's not the case for you (my item list template contains several buttons visible or not depending the item itself, if you only have one button for example, it might be a "lot of work").

So I know I'm not giving you any solution, but maybe just another way to think about how you could solve this specific issue. To summarize:
 - Create custom View (for Android) or UserControl (for WP) for each targeted platform
 - Manually create handlers for these views to send an Message through the IMvxMessenger on clicks or whatever event ou want to catch
 - Use IMvxMessenger to catch Messages and execute your Command

Main advantages I see in this solution too is that you can reuse your view easily and it makes your ViewModel eventually lighter (with less code duplication).

Hoping that helps ;)

**Comment by kiliman** [comment]
Like @sescandell, I also like to use messages.

I created a value converter that converts Commands to Messages. This way I can bind events in the list item layout like I normally do and have it publish a message to any subscribers (usually the parent view model).

```xml
<Mvx.MvxImageView
	android:layout_width="75dp"
	android:layout_height="75dp"
	android:layout_margin="10dp"
	local:MvxBind="ImageUrl ImageUrl; Click CommandToMessage('KittenView.Core.Messages.KittenAcceptedMessage', .)" />
```

See https://github.com/kiliman/MvxCommandToMessage

**Comment by AhmedWarreth** [comment]
Hello,

From a coding prespective, the Commands to Messages approach seems like the cleaner approach. Can anyone an more info on this? performance wise?

**Comment by L3xer** [comment]
I'm working on MvvxCross clone of iOS AppStore 

![2017-12-02_09-33-35](https://user-images.githubusercontent.com/8818052/33513046-f9a0440e-d743-11e7-85b7-a38901d6541f.png)

and want to bind click on an individual app to my ViewModel command.

**Comment by nickrandolph** [comment]
@hugoterelle is this issue still outstanding?

**Comment by hugoterelle** [comment]
From my point of view, not.  But I didn't follow the latest developments of MvvmCross since a while.
