### ISSUE TITLE
[Bug] [iOS] Page with top toolbar have extraspace when rotate from landscape to portrait and viceversa

### ISSUE THREAD

**Issue by Sonic3R** [MvvmCross/MvvmCross#3707]
### Expected behavior
In master detail page, if you have toolbar with primary and secondary orders, if rotate (from landscape to portrait OR portrait to landscape) that page then under secondary order toolbar items will exists an extra white space.

It occur on both iPad (physical and emulator). On UWP, works fine, no extra space added.

### Reproduction steps
1. Go to `Master Detail Page`
2. Swipe from left to right to open left menu and select `Contact`
2. In detail page, rotate iPad (physical or emulator)
3. You'll see extra space below secondary order toolbar items

### Configuration

**Version:** 6.4.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

### Screenshots

![image](https://user-images.githubusercontent.com/6311947/74011432-8133df00-4990-11ea-86e4-b9cd7a0e32a7.png)

### Reproduction Link
[MasterDetailDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4169586/MasterDetailDemo.zip)

**Comment by Cheesebaron** [comment]
Have you tried reproducing this in Xamarin.Forms without MvvmCross?

**Comment by Sonic3R** [comment]
> Have you tried reproducing this in Xamarin.Forms without MvvmCross?

It works without MvvmCross

**Comment by DaniRvd** [comment]
When you open for the first time contact details page , can you see the text "Welkom to contacts page" ?
But after rotate the tablet then can you see the text?
This is the problem the content of detail page is displayed first behind of toolbar after you rotate the tablet page is auto resized and text become visible.
![74030796-96246880-49b8-11ea-84a8-8bc62def8452](https://user-images.githubusercontent.com/20532118/75329915-2d2e6300-5889-11ea-9602-9b65b46176c3.png)
![74030842-b2c0a080-49b8-11ea-8a43-c75a09fe3f61](https://user-images.githubusercontent.com/20532118/75329919-2f90bd00-5889-11ea-9917-053cc8ed5fcb.png)
![74030989-12b74700-49b9-11ea-9a9b-dcf760e04d9f](https://user-images.githubusercontent.com/20532118/75329923-31f31700-5889-11ea-9666-58a1b5828bf1.png)
![74031074-44c8a900-49b9-11ea-996f-50030b4569c5](https://user-images.githubusercontent.com/20532118/75329930-34557100-5889-11ea-8984-e9433e6e19d6.png)

I think the problem whit white/blank space appear when you want that "Welcome to ContactPage"to be visible for the first time.
If you set top margin for the StackLayout you can see that "Welcome to ContactPage" is visible for the first time ( third screen shot) but after rotate the tablet or simulator you will get the white/blank space (fourth screen shot).

To simplify the problem i think we can say that the issue is that "Welcome to ContactPage" is not visibile for the first time
