### ISSUE TITLE
ResxLocalization plugin doesn't works in Xamarin.Forms UWP projects

### ISSUE THREAD

**Issue by LITTOMA** [MvvmCross/MvvmCross#3774]
## 🐛 Bug Report

I'm using the ResxLocalization plugin in a UWP project but it can't load string resources.
However, it works for Xamarin.Forms.Android and Xamarin.Forms.iOS.

### Reproduction steps
I created a sample project for this:
https://github.com/LITTOMA/ResxLocalizationTest

**Version:** 6.4.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LITTOMA** [comment]
8 months past...

No comments.
No assignees.
No labels.

Okay...

**Comment by StevenBonePgh** [comment]
Apologies for not seeing this earlier, as I was also hit with this (or a strikingly similar) problem. Getting Resx Localization to work is really hard. 

First issue: I see that the string resource in your sample repro has a period in the name `"MainViewModel.StrHello"`. This is not an issue with MvvmCross, but rather an incompatibility with the rest of the world by UWP.  In UWP, periods need to be replaced by a slash when accessing it, though this would then break the other supported platforms. The only 'real' solution is to avoid periods. References: https://stackoverflow.com/a/50651824/1185620, https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest I raised issue #2926 that could resolve this, but the maintainers have not indicated what approach to fixing it they would accept as a PR so I have not made one.

Second issue: A NetStandard library with resources requires you to set add the following (which traditionally went into AssemblyInfo.cs) `[assembly: NeutralResourcesLanguage("en-US")]` Obviously use the proper culture for your use case.

Third issue: In your demo project this is correct, but I add it here for the sake of completeness. In the UWP head project csproj, you must define a default language, by adding `<DefaultLanguage>en-US</DefaultLanguage>` to an unconditioned `<PropertyGroup>`. Obviously use the proper culture for your use case.

One last thing on UWP. When calling ResourceManager.GetString(string name, CultureInfo culture) with the same value for name using culture 'x' then calling it again for culture 'y' will return the same string even if it should differ by culture. The only workaround was to call it a second time with culture 'y'. I don't know if this is still an issue in the field or not but worthy of comment because it drove me nuts.

**Comment by StevenBonePgh** [comment]
Apologies for not seeing this earlier, as I was also hit with this (or a strikingly similar) problem. Getting Resx Localization to work is really hard. 

First issue: I see that the string resource in your sample repro has a period in the name `"MainViewModel.StrHello"`. This is not an issue with MvvmCross, but rather an incompatibility with the rest of the world by UWP.  In UWP, periods need to be replaced by a slash when accessing it, though this would then break the other supported platforms. The only 'real' solution is to avoid periods. References: https://stackoverflow.com/a/50651824/1185620, https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest I raised issue #2926 that could resolve this, but the maintainers have not indicated what approach to fixing it they would accept as a PR so I have not made one.

Second issue: A NetStandard library with resources requires you to set add the following (which traditionally went into AssemblyInfo.cs) `[assembly: NeutralResourcesLanguage("en-US")]` Obviously use the proper culture for your use case.

Third issue: In your demo project this is correct, but I add it here for the sake of completeness. In the UWP head project csproj, you must define a default language, by adding `<DefaultLanguage>en-US</DefaultLanguage>` to an unconditioned `<PropertyGroup>`. Obviously use the proper culture for your use case.

One last thing on UWP. When calling ResourceManager.GetString(string name, CultureInfo culture) with the same value for name using culture 'x' then calling it again for culture 'y' will return the same string even if it should differ. The only workaround was to call it a second time with culture 'y'. This was so terrible

**Comment by StevenBonePgh** [comment]
@LITTOMA 7 days past...

No feedback on my response. Providing feedback on a proposed solution helps others.

**Comment by LITTOMA** [comment]
@StevenBonePgh Sorry, kept you waiting, huh?

Thanks for your reply.
I tried to remove the class name and period in the resource name. It works properly.
See:

> ResxLocalizationTest #[f8890f8](https://github.com/LITTOMA/ResxLocalizationTest/commit/f8890f81940832d75c0d90cbe2070986d9731982)


So for those who want to add localization support for Xamarin.Forms.UWP,
I suggest you don't create string resources in ClassName.ResourceName format, just make it globally.
Like 
``` xml
  <data name="StrHello" xml:space="preserve">
    <value>Hello</value>
  </data>
```
And to get the "global" string resource, you can just create a MvxLanguageBinder object with no parameters passed to the constructor:
``` csharp
IMvxLanguageBinder TextSource => new MvxLanguageBinder();
```
