### ISSUE TITLE
Refactoring the startup and asynchronously.

### ISSUE THREAD

**Issue by andres-gimenez** [MvvmCross/MvvmCross#3854]
## 🚀 Feature Requests

I've detected problems in the code and I'd like to fix them. Most related to asynchronous management. Asynchronouss appeared with net4.5 and has evolved a lot since then. And he has a better chance.

### Contextualize the feature

The goal is to improve the start. 

1. Make concurrency control more robust. 
2. Support for more platforms (e.g. webassambly with blazor).
3. Get as asynchronous an interface as possible.

### Describe the feature

ConfigureAwait(false) must be indicated in all asynchronous files.
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
https://devblogs.microsoft.com/dotnet/configureawait-faq/

Refactorizar MvxSingleton, usando Lazy y AsynLazy. This allows for a more stable start. And to be able to create an asynchronous boot. For the processor cores to be used.

Minimize the use of Lock. And never about non-private objects.

Not use GetAwaiter().GetResult(); It usually produces hard locks At least in UAP.

In the common part to all platforms only use async, await, Task, and ValueTask. Each platform has its uniqueness with asynchronous programming. Using TaskCompletionSource is useful for converting a non-asynchronous interface to asynchronous. But about UAP, it's problematic.

Use ValueTask instead of Task. Improves performance.  #3814

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms
- [x] :🌍: Blazor

**Comment by Cheesebaron** [comment]
For `ConfigureAwait(false)` you write:

> ConfigureAwait(false) must be indicated in all asynchronous files

That is not correct. It is needed in cases where you are _not_ interested in returning to the capture context. This is not _always_ the case. So blindly adding it everywhere doesn't really solve anything.

As for `GetAwaiter().GetResult()`. It can be necesasary to use that if you are starting something from a method that is not async and where you cannot await and you actually need the result after. However, it can be dangerous especially if something else is trying to do stuff on the same SynchronizationContext we call `GetResult()` on.

MvxSingleton doesn't have any async code. It won't benefit from using anything lazy in here, it is just a singleton.

The issue with startup is that we want to block anything else from running until MvvmCross actually has started. That is why we do that in a blocking manner. That is why if you do something in `InitializeAsync` that tries to return to SynchronizationContext it breaks startup. Adding ConfigureAwait blindly all over the place doesn't change that fact.

**Comment by andres-gimenez** [comment]
Read this article
https://devblogs.microsoft.com/dotnet/configureawait-faq/

> Why would I want to use ConfigureAwait(true)?
> You wouldn’t, unless you were using it purely as an indication that you were purposefully not using ConfigureAwait(false) (e.g. to silence static analysis warnings or the like). ConfigureAwait(true) does nothing meaningful. When comparing await task with await task.ConfigureAwait(true), they’re functionally identical. If you see ConfigureAwait(true) in production code, you can delete it without ill effect.
> 
> The ConfigureAwait method accepts a Boolean because there are some niche situations in which you want to pass in a variable to control the configuration. But the 99% use case is with a hardcoded false argument value, ConfigureAwait(false).

In teh tests I' ve done, I only needed .ConfigureAwait(true) on one occasion. In a library is is advisable use .ConfigureAwait(false)

> MvxSingleton doesn't have any async code. It won't benefit from using anything lazy in here, it is just a singleton.
Most may not need asynchronous booting.

In previos versions if you weren't using GetAwaiter().GetResul() the Task not run. But now if you call an asynchronus function, it usually runs. You may need GetAwaiter().GetResult() on iOS and Android, but on Windows it gives problems. In Convertes may need to be needed. But not in the commands.

With InitalizeAsync, that's what I want to change. Do not block until everything is initialized. I want them to start in the background. And hide the home screen as soon as possible. And have them initialize in parallel if possible. That's why I want to use an AsyncLazy

**Comment by Cheesebaron** [comment]
I know what `ConfigureAwait(false)` does. I just explained it and the article you linked just confirms that. What is your point? Still adding `ConfigureAwait(false)` everywhere doesn't solve anything.

You are confusing `MvxSingleton` with `MvxSetupSingleton`.

We are using `GetAwaiter().GetResult()` 3 places:

https://github.com/MvvmCross/MvvmCross/blob/4b14fbf95b6d886bb5e36c31e2afd4c28a8c0caf/MvvmCross/Core/MvxSetupSingleton.cs#L116

https://github.com/MvvmCross/MvvmCross/blob/a12c58d90af10741def51ae84cf1c108b66c0e30/MvvmCross/ViewModels/MvxAppStart.cs#L28

https://github.com/MvvmCross/MvvmCross/blob/a12c58d90af10741def51ae84cf1c108b66c0e30/MvvmCross/ViewModels/MvxAppStart.cs#L108

These are there _intentionally_, to block execution of anything else until MvvmCross is done. If we just let execution continue and MvvmCross is loading in the background, everything will blow up on the first ViewModel because nothing is done loading yet.

Startup methods are running in parallel, but it is _not_ winning any time since the methods are running quite fast to beging with and the time we win is eaten by overhead anyways. If you want fast startup use profiled AOT startup on Android. iOS is already AOT.

**Comment by andres-gimenez** [comment]
The don't put. ConfigureAwait(false) can give someone problems, because the original context is lost. 
That is why it is recommended to put it (RCS1090). It also improves performance.

MvxSingleton.  I want to take it off. The only utility is for unit tests. And there's another pattern. 
MvxSetupSingleton. I don't if it's simplified, or also removed. And replace with Lazy.

Here's https://github.com/MvvmCross/MvvmCross/issues/3213#issuecomment-652492077 an example where GetAwaiter().GetResult(); cause problems. Change is not easy. That's why refactoring.

AOT is not as efficient. My client don't like it. Charging time is somthing that is hightly valued. And I have App, they do more things in the load.

**Comment by andres-gimenez** [comment]
You have to value, that the changes I want to make, lowers the complexity. And it will be easier to implement other platforms.

I see you've been trying something with Uno Platform.

**Comment by Strifex** [comment]
@andres-gimenez please re-read some of the articles you linked and try to put it into context.  What @Cheesebaron is saying is correct.  The article you linked on using ConfigureAwait(false) for libraries is in the context of "general purpose" libraries, ones that don't necessarily matter in the context of UI or platforms where "thread context" is important, which is why the author points out that ConfigureAwait(false) can be a benefit.  However, I think you fail to realize that because this is a UI Framework, there are certain calls and certain areas in the application that will need to await true because the library call may need to chain and assume its being called from the main thread or returning on that particular context.  This is never going to be as simple as "Switch everything to ConfigureAwait(false)" - this would take careful analysis of each flow where its utilized to see what makes sense and where it actually matters.  So please stop claiming its better to always turn it off in a library, as it contributes to the spread of misinformation.

**Comment by andres-gimenez** [comment]
I see there's not much interest in the changes I propose. I'll try to solve the problems I have otherwise.

**Comment by Cheesebaron** [comment]
@andres-gimenez it is not that there aren't any interest in your changes. They just seem "random" and untested. I'll repeat myself once again. Adding `ConfigureAwait(false)` all over the place doesn't _solve_ anything if the intention to begin with, was to return to the context that was captured in the particular case.
