### ISSUE TITLE
PreferenceFragment target bindings missing after migration to AndroidX

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#4094]
## 🔙 Regression

PreferenceFragment target bindings were removed when we migrated to AndroidX. These classes are missing: https://github.com/MvvmCross/MvvmCross/tree/6.4.2/MvvmCross.Android.Support/V7.Preference/Target and not registered during setup.

See https://github.com/MvvmCross/MvvmCross/discussions/4091

### Old (and correct) behavior

You could access BindValue, BindText, BindClick and BindChecked on Preference types

### Current behavior

These are now gone

### Configuration

**Version:** 7.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by DavidMarquezF** [comment]
I followed your suggestion #4091 and migrated them to AndroidX. I attach here the code so that if anyone also needs it they don't have to do the same process. I tried it on my app and works, so I suppose there shouldn't be any problems. If @Cheesebaron wants, I can try to do a pull-request when I can.
[MvxPreferencePatch.zip](https://github.com/MvvmCross/MvvmCross/files/6008611/MvxPreferencePatch.zip)
