### ISSUE TITLE
Future of MVVMCross with .NET 6.0 and MAUI

### ISSUE THREAD

**Issue by ghost** [MvvmCross/MvvmCross#4138]
I currently develop a mobile application using Xamarin.Android and MVVMCross.

My understanding is that Xamarin.Native (Xamarin.Android and Xamarin.iOS)  will now be part of .NET 6.0 when it is released in November 2021

Will this affect the development of MVVMCross and will MVVMCross going to continue to support this.

It would be useful to have an idea of the way forward, just in case there is any significant work required in my application.

Any information would be really helpful

**Comment by Cheesebaron** [comment]
Hopefully it is just a matter of changing the TFM to `net-android` and `net-ios` instead of `xamarin.android` and `xamarin.ios`. As for MAUI support, it might not be the first thing to be supported, but the new TFMs most definitely.

**Comment by user-mmc** [comment]
@Cheesebaron Thanks for responding so quickly. So it seems that support for Xamarin.Native (as it called today) will continue in MVVMCross beyond the introduction of MAUI.

Forgive my ignorance what does TFM stand for?

**Comment by Cheesebaron** [comment]
TFM stands for Target Framework Moniker 😄

**Comment by user-mmc** [comment]
Thanks

**Comment by rafalka** [comment]
@Cheesebaron May I know when (approximately) MAUI be supported? 
We starting new project and we'd like to move to MAUI once it will be released (desktop is one of our targets). 
We'd like to know if MvvmCross won't block us with that.

**Comment by Cheesebaron** [comment]
For now I don't have any plans on supporting something that is still in preview, I simply don't have time to support it. You can ask again when .Net 6 and MAUI is released.

So my estimate would be, unless someone contributes the support, would be _after_ .Net 6 and MAUI has been released, how long after. I don't know.

**Comment by rafalka** [comment]
Thanks for prompt reply.

I understand your point. 
At least situation is clear for us now.

**Comment by ADRI082** [comment]
I'm migrating a xamarin forms app, which is using mvvmcross, to a MAUI app but when I do this, I get several errors about this framework. Does anyone know if mvvmcross is compatible with MAUI???.

Thank you

**Comment by Cheesebaron** [comment]
We don't have any official support for MAUI. You are welcome to help contribute it.

**Comment by thefex** [comment]
Ideally, I would like to see direction where MAUI (Forms - because this is just Forms rebranded, perhaps with more resources applied to this) is just complementing MvvmCross development - where you use native dev with MvvmCross and use MAUI to implement easy views (like menu view, registration etc..) - just to save some time.
Basically, all of the mobile platforms allows for modular implementation. We have Activities & Fragments  for Android,  ViewControllers for iOS, Pages for WPF etc... Therefore it is technically possible to mix that.
I think if you still use MvvmCross then probably, you've already know that "single-shared-UI" is utopia. Does not mean that Forms/MAUI is useless though.

I've just developed proof-of-concept for MvvmCross forms-bridge and will happily move that to Maui when it's stable. See: https://github.com/thefex/MvvmCross.FormsBridge.Template 
I'd like to push pull request for that but don't have access to Windows now (can't build) ;/

**Comment by JelleDamen** [comment]
> We don't have any official support for MAUI. You are welcome to help contribute it.

I would love to help with the Mvx support for Maui. I haven't looked at the latest previews of .net 6, do you know if it is already usable/complete ?

**Comment by Cheesebaron** [comment]
I recently gave preview.6 a spin. Seems to be ready soon.

I think the main issue currently is to switch the pipeline to use the new .net6.0 stuff and preview versions of tooling.

**Comment by AndrewBryanScott** [comment]
its runs ok in emulators, once you start looking at getting it to run and deploy to actual devices you run into roadblocks, there is  Zero documentation yet and  you cant run or deploy the UWP targets yet in VS 2022 17.0.0 preview 3.1, bit of mess still, I and believe it will take a bit longer to get stable once they release it in November with .Net 6

**Comment by OmegaRogue** [comment]
Any Update on this now that .net6 is released?

**Comment by Cheesebaron** [comment]
@OmegaRogue yeah, I have a branch and PR #4319 open. Just need to finish it up.

**Comment by domedellolio** [comment]
Hi @Cheesebaron one of my customer is asking to provide a plan on when we can start approching the migration to MAUI. 
Since our app is built upon MvvmCross is there any plan to start working as in Q1 2022 MS will release a RC?

Thanks

**Comment by Cheesebaron** [comment]
@domedellolio is your customer or you willing to sponsor the work needed for it? It could be either through a contribution or paying for the work required.

I don't have anything in my schedule right now to support it. I would rather want to focus on other parts.

**Comment by domedellolio** [comment]
Hi @Cheesebaron thanks for your feedback.
How much effort (ROM) do you think is required here? Also to evaluate a possible involvement / investment

BTW, as part of .NET Foundation will MAUI be part of future at some point for MvvmCross?

Thanks

**Comment by Cheesebaron** [comment]
The dotnet foundation doesn't dictate what we support or not.

There is currently only me working on MvvmCross from time to time. So I would prefer to keep the support surface as low as possible.

As for, how much time would be needed to support MAUI, it really depends on what kind of support you need and how deeply you want to integrate.

Since MAUI is using a different IoC container than MvvmCross, I would somehow need a way to support that or as has been planned, switch to the same in MvvmCross.

There is some ongoing work in the .net6.0 migration branch that would help with that, but still a lot work would be needed.

A very careful estimate would be around one weeks worth of work, but there are a lot of unknowns.

**Comment by PradeepPappuAto** [comment]
Hi @Cheesebaron , 
Any updates since your last message?
Could you also share the roadmap for the project please?
Thanks

**Comment by Cheesebaron** [comment]
I don't want to promise anything. I think your best bet would be to just go with another framework. There is not much benefit of using MvvmCross with Xamarin.Forms Apps to begin with.

**Comment by entdark** [comment]
And what about `net6.0-android` and `net6.0-ios`?

**Comment by Cheesebaron** [comment]
That is on the way, last week I checked, still having issues with Nfloat which is blocking me, will try again now that 6.0.300 has been released.

**Comment by vedecoid** [comment]
"There is currently only me working on MvvmCross from time to time", in other words, better stay away from the framework unless it already does everything one could possible want...

**Comment by nabond251** [comment]
As a fellow framework dev, I just want to say thank you @Cheesebaron for your efforts. This is all free stuff you've carved out precious time to work for us, and that is appreciated.

**Comment by nabond251** [comment]
@vedecoid with all due respect, is it fair to expect all that? Alternatively there's nothing stopping you or others from pitching in, as has been stated a few times.

**Comment by Cheesebaron** [comment]
> "There is currently only me working on MvvmCross from time to time", in other words, better stay away from the framework unless it already does everything one could possible want...

By all means stay away. No one is forcing you to use MvvmCross. However, your comment is off-topic, please leave that out of the discussion.

**Comment by vedecoid** [comment]
Off topic ? Someone is asking if you will support .net Maui and the response is : dunno, maybe if i feel like it because i’m the only one working on it. I will for sure stay away. Started with mvvmcross 10 years afo on release 3.x. Then spend countless hours with every iOS upgrade that also required an mvvmcross upgrade to correct all the breaking changes. We stopped it already after v6 as it just wasn’t worth it anymore. Also meant we had to rewrite our app from scratch.. Look, i have a lot of admiration for you guys doing all this work basically for free. But if you advertise a framework the way mvvmcross was advertised, with James Montemagno bringing it on Channel9 and beyond, then people expect there more than 1 very brave guy working on it.

**Comment by thefex** [comment]
> Off topic ? Someone is asking if you will support .net Maui and the response is : dunno, maybe if i feel like it because i’m the only one working on it. I will for sure stay away. Started with mvvmcross 10 years afo on release 3.x. Then spend countless hours with every iOS upgrade that also required an mvvmcross upgrade to correct all the breaking changes. We stopped it already after v6 as it just wasn’t worth it anymore. Also meant we had to rewrite our app from scratch.. Look, i have a lot of admiration for you guys doing all this work basically for free. But if you advertise a framework the way mvvmcross was advertised, with James Montemagno bringing it on Channel9 and beyond, then people expect there more than 1 very brave guy working on it.

". Also meant we had to rewrite our app from scratch." - so if you guys earn $$$ on your work, then spend some $$$ on capital investments into MvvmCross - otherwise you should not expect anything and move on to other tools - good luck though, there is no better way to develop mobile in Xamarin though (pushed&managed&lead dozens of Mvx production apps, some of them for *big* institutions - no any issues at all) :)  
As far I recall Tomasz ( I used to develop bunch of things here few years ago ) never advertised this framework in aggressive way -  it's been always given 'you get what you get, if you want to get something quickly do it yourself and make PR'.

**Comment by vedecoid** [comment]
It was a free app. This debate clearly illustrates the limits of the Open Source model. Unless you’re willing to always have the risk of discontinuation, you better go with commercial tools. They at least care about their users out of necessity. We’ve learned our lesson.

**Comment by vedecoid** [comment]
And btw, Xamarin is history. Will go out of support in 2024.

**Comment by thefex** [comment]
Xamarin might be a history but MAUI is not. As MAUI use native controls (native SDKs) to render UI that means it will not go out of support and native dev will be available.
MvvmCross been heavily supported over many years, I think I've been using it since 2015? 
Mobile development (and the enormous pace SDK's evolve - in opposite to ex. backend/database development) - means breaking changes here are something expected and not unusual.

**Comment by vedecoid** [comment]
Well, then you better wake up to the music, because Tomasz, the only brave developer left said he doesn’t see the need to support Maui, which started this whole debate.

**Comment by thefex** [comment]
You clearly don't understand what you are talking about :)
Tomasz said he will release .NET 6.0 support. If he won't release that, I will pick and complete that. Therefore, native development will still be available. MAUI uses native SDKs and native tooling to produce builds.
MAUI-XAML-multiplatform support is a different story. If you want to go full xaml/full MAUI-views (as it was with Forms) then there is no really need/much benefit of using MvvmCross as framework. 

I (and many other devs) will keep building native apps anyway - I plan to create a bridge where I will consume some MAUI/XAML views in addition inside MvvmCross/native app. Right now, it's too early to bother, MAUI is RC, not production ready.

**Comment by vedecoid** [comment]
Good for you. And no, i do know what i’m talking about. Ten years ago, using 3.x you had to to get anything working. Again, the thread started with somebody asking if the ‘easy multiplatform maui’ would be supported. The right answer clearly is: there’s no need, so if that is the perimeter one needs, one better stays away from Mvx, which was my whole point. But i stay withnmy conclusion that a framework, no matter how good it is, is only supported by a handful or a single person, then better stay away from it
