### ISSUE TITLE
Localization feature doesn't works

### ISSUE THREAD

**Issue by 2urbo** [MvvmCross/MvvmCross#4208]
## 🐛 Bug Report

Localization feature doesn't work after upgrading to version 8:

`GetText` method from `MvxLanguageBinder` throws the following exception:
> MvxException: 'Missing text provider - please initialize IoC with a suitable IMvxTextProvider'

`MvxResxTextProvider` is registered in the App.cs file and can be successfully resolved using `Mvx.IoCProvider.Resolve <IMvxTextProvider>()`.

### Expected behavior

`GetText` returns localized string.

### Reproduction steps

1. Register `MvxResxTextProvider` in App.cs file:
```csharp 
Mvx.IoCProvider.RegisterSingleton<IMvxTextProvider>(new MvxResxTextProvider(StringResources.ResourceManager));
```
2. Call the `GetText` method:
```csharp 
var languageBinder = new MvxLanguageBinder();
languageBinder.GetText("LocalizedString");
```
### Configuration

**Version:** 8.0.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
App.Initialize happens _after_ plugin registration, you need to initialize the IMvxTextProvider earlier.

**Comment by Krusty93** [comment]
> App.Initialize happens _after_ plugin registration, you need to initialize the IMvxTextProvider earlier.

Such as where?
I can't see anything [in the documentation](https://www.mvvmcross.com/documentation/upgrading/upgrade-to-mvvmcross-80?scroll=1736), and basically all the MvvmCross.Plugin.ResxLocalization.resx tutorials put the registration (`Mvx.IoCProvider.RegisterSingleton<IMvxTextProvider>(new MvxResxTextProvider(AppResources.ResourceManager));`) into `App.Initialize` because it used to work with the old versions.

I've tried to put it into `Setup.LoadPlugins` or `Setup.InitializeFirstChance` but with no luck.

Cheers
