### ISSUE TITLE
Navigation with param and result crash on back navigation

### ISSUE THREAD

**Issue by rkotulan** [MvvmCross/MvvmCross#4226]
### Current behavior
Call
result = await navigationService.Navigate<ServiceDetailPageViewModel, ServiceDetailParameters, BoolDialogResult>(param);

when I close ServiceDetailPage with the back button app crashes.

### Expected behavior
Close the ServiceDetailPage and navigate back to the call method and return the result.

### Investigation
Class
MvxNavigationService.cs

Method (line 355)

`
protected virtual async Task<TResult?> Navigate<TParameter, TResult>(MvxViewModelRequest request,
            IMvxViewModel<TParameter, TResult> viewModel, TParameter param, IMvxBundle? presentationBundle = null,
            IMvxNavigateEventArgs? args = null, CancellationToken cancellationToken = default)
            where TParameter : notnull
            where TResult : class
`
at the end is

`
return (TResult?)await tcs.Task.ConfigureAwait(false);
`

should be

`
try
            {
                return (TResult?)await tcs.Task.ConfigureAwait(false);
            }
            catch (Exception)
            {
                return default;
            }
`

### Configuration

**Version:** 8.0.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by alyxal** [comment]
We're still having the issue in 8.0.2.

After investigating, it seems like 
`Navigate<TViewModel, TParameter, TResult>(
TParameter param, 
IMvxBundle? presentationBundle = null, 
CancellationToken cancellationToken = default)` 

actually calls 
`Navigate<TParameter, TResult>(Type viewModelType, TParameter param,
IMvxBundle? presentationBundle = null, CancellationToken cancellationToken = default)`

and finally ends up in 
`
Task<bool> Navigate(MvxViewModelRequest request, IMvxViewModel viewModel,
IMvxBundle? presentationBundle = null, CancellationToken cancellationToken = default)
`

It doesn't use the function fixed by #4230
