### ISSUE TITLE
Remove broken Navigate methods that pass back data when calling Close

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#4262]
## 🐛 Bug Report

We have a way of awaiting data from a ViewModel you navigate to through the NavigationSerivce. This is inheritly broken, since there are many cases, such as tombstoning the App, and other platform specific navigation paradigms that are hard to shoehorn into this navigation pattern.

This interface should be removed because it is broken by design.

Example:

```csharp
var result = await NavigationService.Navigate<MyViewModel, SendingParams, ResultParams(mySendingParam);
```

in MyViewModel:

```csharp
await NavigationService.Close<ResultParams>(result);
```

The await for getting the result often breaks, especially when navigating more levels into the stack and when app is tombstoned.

### Configuration

**Version:** 6.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by devintivie** [comment]
I'm also seeing this behavior when not returning a result. Using standard navigation then pressing the back button makes the command unable to be called. This seems to be caused by GC and potentially because MvxAsyncCommand uses WeakReference, I will copy and paste exact comment later but am struggling to find workaround.
