### ISSUE TITLE
Including mac build in nuget

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#502]
Hi, I was thinking that in the build for nuget you can include the .Mac components as well. You can compile the libraries by adding Xamarin.Mac or MonoMac.dll to Windows. Then add it into a "mac" folder. Even though it won't really pick up, the folder will be there and we can manually point to the package folder.

**Comment by martijn00** [comment]
@lothrop Didn't you do something on this?

**Comment by slodge** [comment]
Sadly I think this issue still sits in the realms of `hard to do` - maybe only possible using yucky powershell scripts (which then might not run on mac or depending on security permissions or...yuk).

The problem is that nuget sees the same "normal PC app" project type for all of:

- WPF csproj files
- Console csproj files
- MonoMac csproj files
- XamMac csproj files

So, how does nuget choose which set of assemblies to install?

Currently, this is low priority still - as the 99% of our users facing this choice are on `WPF` - but if C# is to succeed on Mac, then someone should work this out... (probably at a nuget repo level)

**Comment by lothrop** [comment]
Sorry, didn't touch the Nuget stuff. But I've added a third Mac project type to worry about, which might make things even more complicated.
