### ISSUE TITLE
XamMac vs MonoMac

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#516]
It seems that to support XamMac as well as MonoMac there needs to be a mirror of all the Mac files, but using XamMac.dll instead of MonoMac.dll. We can use linked files, but it still is not pretty. I suspect we'll end up with projects and separate nuspecs for MonoMac and XamMac.

**Comment by martijn00** [comment]
@lothrop Didn't you do something on this?

**Comment by lothrop** [comment]
No, I contributed to the mess. We now have other projects (Xam.Mac.Unified) using file linking. One alternative would be shared projects but this would mean even more project files since we still need the native project files referencing a common shared project.

The Unified projects also use #if because of namespace and type changes. Not entirely happy with that. Perhaps they should be sharing code with iOS. For that, we'd need someone with a lot of Xamarin.Mac experience to do that change.
