### ISSUE TITLE
Instantiating MvxCommand crash

### ISSUE THREAD

**Issue by sschoeb** [MvvmCross/MvvmCross#650]
Just updated to the latest and greates beta.

When I run my UnitTest they now fail with a NullPointException when instantiating MvxCommand.

Trace:
reference not set to an instance of an object.
    at Cirrious.CrossCore.Mvx.TryResolve(ref TService service)
   at Cirrious.MvvmCross.ViewModels.MvxCommandBase..ctor()
   at Cirrious.MvvmCross.ViewModels.MvxCommand..ctor(Action execute, Func`1 canExecute)
   at PortableCommandTest.Class1..ctor() in Class1.cs: line 18
   at CommandsTest.UnitTest1.TestMethod1() in UnitTest1.cs: line 13

I just don't get it what can be wrong here?

Sample repository can be found here:
https://github.com/sschoeb/CrashMvxCommand

This does work with the latest stable and fails with the newest beta

Additional notest to the demo repo:
There is one test-Project with a single Unit test and a "Core"-PCL with the Class1.
Class1 does contain a Command property which is instantieted in the constructor. When running the UnitTest it will fail...

**Comment by RandomEngy** [comment]
This is rather annoying. Every single viewmodel has MvxCommands in it and now all of their unit tests need some special IoC setup in order to run? Also shouldn't we be able to pick and choose pieces rather than take the whole enormous system, IoC and all? We are quite happy with our existing Unity IoC and would like to use MvvmCross for the viewmodels and data binding only.

**Comment by Cheesebaron** [comment]
And you propose what exactly?

**Comment by RandomEngy** [comment]
That you be able to make an MvxCommand without calling an IoC setup method? Or provide an ICommand implementation that doesn't have dependencies like this. Or use a ServiceLocator pattern so you don't statically bind into one particular IoC framework. I don't know the codebase incredibly well so there may be some reasons why it's impossible, but it certainly would be very nice.

**Comment by Cheesebaron** [comment]
I don't see how using the ServiceLocator pattern would solve anything, it would just move the problem elsewhere. In fact, MvvmCross does provide the ServiceLocator pattern.

You are not forced to use the built in IoC: https://github.com/MvvmCross/MvvmCross/wiki/Service-Location-and-Inversion-of-Control#what-if-i-want-to-use-a-different-service-location-or-ioc-mechanism just provide the interfaces yourself...

**Comment by slodge** [comment]
As the great cheese says - https://github.com/MvvmCross/MvvmCross/wiki/Service-Location-and-Inversion-of-Control#what-if-i-want-to-use-a-different-service-location-or-ioc-mechanism

And for examples of plugging in your own IoC, see posts like http://stephanvs.com/how-to-replace-mvvmcross-ioc-with-autofac/, http://blog.rthand.com/post/2014/01/20/Using-Autofac-with-Xamarin.aspx, and https://nbevans.wordpress.com/2014/02/17/xamarin-mvvmcross-with-autofac/

> shouldn't we be able to pick and choose pieces 

Yes - and we've gone out of our way to try facilitate this.

**Comment by RandomEngy** [comment]
Thanks for the pointers on that; I had assumed the reason the command property creation was failing was due to a specific IoC lookup. I still don't quite understand how it's impossible to create an MvxCommand without first doing some sort of IoC setup. Usually you don't have to mess with IoC in unit tests; you just do direct injection of mocks.
