### ISSUE TITLE
New Relic

### ISSUE THREAD

**Issue by igonzalez3314** [MvvmCross/MvvmCross#723]
I am trying to use New Relic Agent (https://github.com/nberardi/newrelic-mobile-xamarin) in iOS app that also uses MvvmCross v3. It works fine in iOS Simulator (6.1 and 7.1 version) but it crashes when it is deployed to iPhone.

When window.MakeKeyAndVisible is called in AppDelegate FinishedLaunching method, the ViewDidLoad method of the startup view is called time and time again until app crashed.

Any clue will be appreciated.

**Comment by RTodorov** [comment]
Hello guys,

There have been any evolution on this matter? I just binded the latest version of NewRelic agent and everything works fine except the Interaction Monitoring when using MVVMCross. Looks like the same issue reported on this thread.

I know about NR being closed source and all but I'm just wondering if something happened since August 2014.

Both MVVMCross and NewRelic are great tools, I can't live without them on my apps, so I gotta make them work together no matter what!

Thanks for any clues!

**Comment by Cheesebaron** [comment]
I doubt it. We can't debug New Relic as it is closed source. Did you try to talk to the New Relic folks?

**Comment by RTodorov** [comment]
Yes, I tried talking to them  a couple of times, apparently they don't give a damn about Xamarin. In fact, I feel like Xamarin could help us a lot more with this issues, they should be harassing the NewRelic folks, not us. Same for Crittercism, we basically only have Xamarin Insights for app monitoring, which is clearly very far from being enough.

**Comment by pkl728** [comment]
If they don't give a damn about Xamarin I would suggest looking at different providers then.  MvvmCross is open source so it should be more than easy to put together a sample repo and submit it to them showing them the functionality that needs to be fixed.  If you do the leg work and they still won't fix it that kind of shows you right there the kind of company you are dealing with.  The same thing happened to us with Mint Express from Splunk.  We moved on to Raygun and Xamarin Insights.

**Comment by RTodorov** [comment]
@pkl728 It's easier to say than to do, unfortunately there's no better tool than New Relic, specially because all our APIs, webservers etc are already monitored by NewRelic. In my case, New Relic is completely mandatory. Mint Express is another tool that I'm gonna have to deal with very soon..... that's why I think Xamarin should be more helpful on this matter, both New Relic and Mint Express are huge tools on the mobile world, if Xamarin really wants to grow they need to make our lives a little easier when using these common 3rd party tools. I'm sorry but Raygun+Insights is light years behind NewRelic+Mint.

**Comment by Cheesebaron** [comment]
Sorry, complaining here won't get Xamarin to help you. I think you would be way better off complaining to Xamarin directly.

**Comment by RTodorov** [comment]
I'm already talking to Xamarin about it, making the complaint public may help. Also there are other people on this thread willing to use NR.

**Comment by pkl728** [comment]
@RTodorov I completely understand.  I was very frustrated that Splunk seemed uninterested in correcting this issue.  However just to warn you with Mint Express, we recently had to pull it out of our native Android project due to their monitoring solution causing crashes.  We wasted 3 or 4 days trying to figure out what was going on until we stumbled upon a hidden post on Splunk's website saying they had a bug which was causing applications to crash.  That post has since been removed (or at least I can't find it now) and am very weary to trust them again.  I'm hoping crashlytics will do something for us soon!

**Comment by RTodorov** [comment]
@pkl728 Wow! Thanks for the heads up, this is very concerning! The last thing I want to do is add a lousy 3rd party tool to my app. I've suffered with a very similar issue when using PubNub for Xamarin.

**Comment by markgibaud** [comment]
Guys, key thing here is that, like I said in my previous post, vanilla Xamarin works fine with NewRelic, it's only when you hook up MvvmCross. So at the very least we need to go to Xamarin with more specific details of the issue once someone has traced through the Mvx code and seen what's happening (sorry I haven't had time yet :-/) but otherwise they can't be expected to support 3rd party tools like Mvx and even if NewRelic supported Xamarin, they would be off the hook because vanilla Xamarin works?

**Comment by RTodorov** [comment]
I'll try to trace what's happening with Mvx under the hood when the crash
is triggered. If I find anything new I'll add to this discussion.

Em terça-feira, 24 de fevereiro de 2015, Mark Gibaud <
notifications@github.com> escreveu:

**Comment by martijn00** [comment]
Please reopen if this is still relevant.
