### ISSUE TITLE
MvxException when a fragment and activity share a viewmodel

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#846]
I have a MasterDetail activity that holds a fragment for a ListView and they share the same view model.  In OnCreate I get:

Cirrious.CrossCore.Exceptions.MvxException: Problem seen creating View-ViewModel lookup table - you have more than one View registered for the ViewModels

I think this would make sense if they were both activities but since I control the presentation of fragments I don't think I should see this exception.

**Comment by davidschwegler** [comment]
This should be marked as a bug, not a feature request IMO. Being unable to host a fragment in an activity using the same viewmodel as the activity is a very important regression in 3.5.

**Comment by nmilcoff** [comment]
Is this issue still relevant? I agree it is handy to allow two views share a ViewModel type, but it isn't a very common approach. 

That being said, I have used a same ViewModel for an Activity and a Fragment in an app by setting the ViewModel with generics in the Fragment, and "catching" the ViewModelRequest in a custom `MvxAndroidViewsContainer`. If a condition is met there, I start the activity instead of the fragment.

This "solution" works for the case when both Views don't need to share the same ViewModel **instance**.

**Comment by davidschwegler** [comment]
Yes, it is an issue. Sadly, one of a laundry list of reasons why we halted future development with MvvmCross in our flagship app.

**Comment by nickrandolph** [comment]
@nmilcoff is this something you think we should continue development on? Or can we close off this issue (@davidschwegler?)

**Comment by nmilcoff** [comment]
I would say we can close this issue. Having multiple Views for a single ViewModel instance is not something we should encourage.

It's something that should be solved at application level by overriding the default ViewContainer / ViewPresenter.
