### ISSUE TITLE
Can't add NuGet MvvmCross 3.5

### ISSUE THREAD

**Issue by mribbons** [MvvmCross/MvvmCross#888]
http://munkiisoft.com/blog/archive/2014/12/17/trouble-adding-mvvm-cross-3-5-to-portable-class-library.aspx

Apologies if this is already a known issue.

**Comment by Cheesebaron** [comment]
What issue, I don't see any description of the issue. The blog post you've linked to is about Silverlight 5 target in the PCL which is not supported by the profile MvvmCross is using. Care to elaborate?

Next time please don't just link to an off-site resource and describe in details **here** or on StackOverflow (much better there, because I don't believe this is an issue).

**Comment by mribbons** [comment]
OK, I get it now.

For anyone else's future reference if you set the PCL to target SL 8.1 then SL 5 target isn't added automatically.

Thanks.
