### ISSUE TITLE
Mac events

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#922]
'm working on Mac right now, and I was wondering on events, why I have to use string and v => v.Activated does not work

is there something I need to change in the Mac code to allow Events to hook up correctly?

this works: set.Bind (goButton).For("Activated").To (vm => vm.GoCommand);
this doesn't: set.Bind (goButton).For(v => v.Activated).To (vm => vm.GoCommand);

cannot convert lambda expression to delegate type string

**Comment by slodge** [comment]
This is surprisingly hard to do using expressions and reflection - and the apple jit restrictions made it feel impossible on iOS 

The best explanation i can give from this train right now is to suggest you look at how moq tried to do this - it uses dummy handler expressions like `Handler += null` and then cookies them in order to extract the event. Sadly this technique won't work without jit - but it might lead to other suggestions for how to make it with...

**Comment by slodge** [comment]
Sorry... Hit wrong button... Did I mention I'm on a train :)

**Comment by slodge** [comment]
Also wanted to say make it ** work ** not with... Stupid auto correct...

**Comment by tofutim** [comment]
That's funny. Have a safe trip. I'll think about it, but use the string for EventHandlers for now.

**Comment by tofutim** [comment]
This also does not work on the Mac side

set.Bind (goButton).To (vm => vm.GoCommand);

I'll see if I can set up the default "For" to be "Activated"

**Comment by tofutim** [comment]
btw, the error on that last one is 

MvxBind: Error:   3.88 Empty binding target passed to MvxTargetBindingFactoryRegistry
MvxBind: Warning:   3.88 Failed to create target binding for binding  for GoCommand

**Comment by tofutim** [comment]
Strange I recompiled and it works fine now. I did find 

			registry.AddOrOverwrite(typeof (NSButton), "Activated");

**Comment by tofutim** [comment]
Sorry I shouldn't have closed that, I forgot that I added ".For ("Activated")" back in. Without it, even with the registry.AddOrOverwrite, it doesn't work. Odd.

**Comment by tofutim** [comment]
Never mind, I'm not using an NSButton, I'm using an "NSButtonCell". Added that into the register.AddOrOverwrite.
