### ISSUE TITLE
listview.PointToPosition not returning the correct values

### ISSUE THREAD

**Issue by nodoid** [MvvmCross/MvvmCross#926]
I have a simple MvxListView containing two items. I've defined a gesture listener which listens in for the OnFling override which passes a clue to another method that attempts to get the position of the item. For the first item, it returns 1 (which as I understand it is correct). The second item returns -1 which is wrong.

Source code is here : http://pastebin.com/esAecExw

Any ideas?

**Comment by slodge** [comment]
Does it work any differently on a plain Android `ListView`? It doesn't look like there's any Mvx code in the gesture logic.

For general "how do I?" questions, StackOverflow is a better choice - it gets more eyes than Mvx issues (and it helps us keep this place clear for our bugs and issues)

**Comment by nodoid** [comment]
Works fine with a standard ListView which is why I reported it here :)

**Comment by slodge** [comment]
The only thing I can think of that is unusual in the listview and adapter is that the adapter returns null for getitem (jonp's advice for adapters so that xam doesn't run out of java wrappers). 

If you've got a full repro - eg a 1 page app running both listview and mvxlistview in a github repo - then I can take a look ... But not sure I'll find anything though!

**Comment by slodge** [comment]
No further comments here - so closing... also I think this has moved to stackoverflow anyway...
