### ISSUE TITLE
[Feature Request] MvxRequestedBy has more useful property

### ISSUE THREAD

**Issue by yuewah** [MvvmCross/MvvmCross#968]
```csharp
public Action<object> Callback
```

**Comment by slodge** [comment]
When the seagulls follow the trawler, it is because they think sardines will be thrown into the sea.










... or, to put it another way... don't suppose you want to explain a bit more what you are looking for here?

**Comment by yuewah** [comment]
As ShowViewModel can only pass simple parameter, MvxRequestedBy can be used to hold some complex object or non-serializable object, e.g. Action. 

ParentViewModel can show a ChildViewModel with an Action callback for passing data back to ParentViewModel.

**Comment by slodge** [comment]
Still not sure I understand

`MvxViewModelRequest` has to be serializable to be used on Windows and on Android. So it's not obvious how to add an `Action` to all requests.

I guess some sub-set of requests could be set up to provide more programmable behaviour, but I'd worry this would lead to confusion and bugs (to questions like "why did my Action not get called for ...?")

**Comment by yuewah** [comment]
my team always ask for a simple callback instead of having publish and subscribe MvxMessage.

**Comment by yuewah** [comment]
if Action is confusing, how about having a sender object ?

**Comment by Cheesebaron** [comment]
The key is that everything needs to be <ins>_**serializable**_</ins>

**Comment by yuewah** [comment]
I think only parameterBundle and presentationBundle is serializable, but not the whole MvxViewModelRequest class

**Comment by slodge** [comment]
I think it depends on your platform @yuewah 

On some platforms, the default navigation mechanism is to serialize the whole of the request - e.g. see WindowsPhone - https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.WindowsPhone/Views/MvxPhoneViewPresenter.cs#L39 - this line converts the request into a xaml uri complete with path to the view (based on ViewModel type) and the serialized bundles.

Similar things happen on Android - where the whole of the request is turned into an Intent (which is cached by the operating system for "tombstoning" - so the request can be used even after the app has been exited and restarted).

I'm not sure I can see a way around these serializable constraints on those platforms at the moment.

However, if the apps and platforms you are currently looking at do not have this serializable constraint, then there are some ways we can think about this - e.g. these apps could use a class derived from `MvxViewModelRequest` and they could use a custom presenter to pass the special request parameters across. If it then also turns out that this situation is common (if others are going to see similar things) then it would definitely be interesting consider how we might be able to make this pattern available for reuse.

**Comment by cyrilcathala** [comment]
I'm not sure it would be a "best practice" to follow this pattern, mainly for tombstoning reasons as stated by Stuart. Moreover, passing an `Action` is not a good idea, it implies a strong reference with memory leaks and bad things happening ...

Anyway, there are many workarounds such as :
- using a singleton repository to hold the objects you need to pass from one view to another
- using sqlite to persist data and pass only an id as navigation parameter, to retrieve data from the database
- make your complex objects serializable (with an impact on performance during serialization/deserialization)

**Comment by yuewah** [comment]
since my target platform don't have tombstoning, but I will go for @slodge suggestion that having a class derived from MvxViewModelRequest, e.g. MvxViewModelInstanceRequest ( it is already supported, but seems seldom mentioned in mvvmcross wiki )
