### ISSUE TITLE
Q: How old is the MT.D fork inside this codebase?

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#969]
After using MvvmCross for a long time, I just noticed it supports MT.D based UI for iOS.  Is there a way to tell how old that fork of MT.D source is that was checked into MvvmCross?  Is someone keeping them in sync?

**Comment by munkii** [comment]
I was wondering exactly the same thing today. Looking at GitHub (https://github.com/MvvmCross/MvvmCross/tree/c306ba37afd9024f68b7a4f1fedcaf4cf7d01b8d/CrossUI/CrossUI.Touch/Dialog/Elements) I would say the original was put in Nov 2012. There have been bug fixes but no obvious updates just to keep the two in sync. Is the MT.D Repo still being worked on? I thought it was not being updated

**Comment by slodge** [comment]
> Is the MT.D Repo still being worked on?

I don't believe it is. 

Our version was forked "way back" (one of us will have to look at version history to find out more) in order to allow us to add binding. There was no interest from MT.D in accepting any changes back so the fork had to stay. Since then it's up to contributors to help ensure any changes get synced.... but there aren't many changes in MT.D nowadays - forms has kind of replaced it.
