### ISSUE TITLE
I would like to see these updates applied to the MT.Dialog fork

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#972]
Changes were made to MT.D as late as Jan 26, 2015.  I am trying to convert a MT.D app to use MvvmCross without changing the UI creation code.  That means I would like to leave the MT.D code there but just use data binding from MvvmCross.  My MT.D app is based on a later codebase than what is checked into MvvmCross so I can't use the older fork that is in the MvvmCross repo.

**Comment by slodge** [comment]
Our code is forked from the original repo, and the original repo wasn't at all interested in taking back any of our changes.

Since the fork, we have accepted changes/contributions where needed - e.g. for ios styling and functional updates.

> MT.D fork is very old...

Fine the fork is "old". However, MT.D hasn't really been actively developed since the fork.

If there are **specific** things that need to be updated then please do suggest them - and please do also consider making the pull requests - we can get them included :+1:
